use vstd::prelude::*;
use crate::symbol::*;
use crate::word::*;
use crate::presentation::*;
use crate::presentation_lemmas::{lemma_equiv_concat_left, lemma_equiv_concat_right,
    lemma_word_inverse_right};
use crate::benign::{apply_embedding, apply_embedding_symbol, lemma_apply_embedding_concat};
use crate::machine_group::word_power;
use crate::higman_consequences::lemma_equiv_inverse;
use crate::hnn::{hnn_presentation, stable_letter, stable_letter_inv, lemma_hnn_conjugation};
use crate::cohen_layer05::{a_col, b_col, acol_elt, bcol_elt, miller_data, lemma_miller_data_valid};
use crate::miller_collapse::{b_sub, binv_sub, miller_collapse_word, lemma_miller_collapse_word_valid};
use crate::miller_collapse_assoc::conj_t;
use crate::miller_collapse_reln::{col_img_a, col_img_b, lemma_ia_form, lemma_ia_conj, lemma_ib_form};
use crate::miller_collapse_eval::{lemma_emb_gen_power, lemma_apply_embedding_singleton,
    lemma_inverse_b_sub};
use crate::machine_group::{symbol_power, lemma_symbol_power_valid};
use crate::normal_form_afp_textbook::lemma_right_cancel;
use crate::britton_infra::lemma_hnn_presentation_valid;

verus! {

// ===========================================================================
// GAP-1 §9.2-item-(2) — `embedding_injective` (the faithfulness "boss fight").
//
// `docs/final-gate-axiom-removal-plan.md` §12.  Goal: the collapse `emb_M : G^(M) → K_M = ⟨a,t|D̄_M⟩`
// is INJECTIVE — `K_M`-equiv of `emb_M`-images ⟹ `G^(M)`-equiv.  This is Miller Thm 4.1's
// **Tietze collapse is an isomorphism** (`docs/higman-embedding-blueprint.md` §"Build order" step 2,
// p.108: "b = tat⁻¹ and each cᵢ = uⱼ(a,t), so G is 2-generated by {a,t}; Tietze to ⟨a,t|D̄⟩").  The
// proof is the **mutually-inverse-homomorphisms** technique (`cohen-faithfulness-primary-source.md`
// §54: "Two mutually-inverse homomorphisms ⟹ isomorphism.  No Britton-peel.") — a SECTION/RETRACTION
// argument that needs NO freeness (the `conj_family`/§D-probe freeness is the SEPARATE `C₀ ↪ G`
// HNN-faithfulness, Layer 0.5, not this Tietze iso).
//
// Route (companion-validated, textbook-confirmed):
//   * ψ : K_M → G^(M),  a = Gen(0) ↦ Gen(n),  t = Gen(1) ↦ Gen(n+2)  (inclusion of the 2 gens);
//   * ψ∘emb_M, as an embedding on G^(M)'s OWN generators, is exactly `miller_collapse_emb(n,n,n+2)`
//     (the routing-neutral "wrap-in-place" instantiation a_idx=M, t_idx=M+2 — designed for this);
//   * `lemma_wrap_is_identity`: that composite ≡ identity in G^(M) (per-generator: a/t trivial,
//     b = tat⁻¹ from the base association, cⱼ = uⱼ from the j-th association solved + b-substitution);
//   * ψ is a valid hom (its only relators D̄_M = emb_M(decls) push back to decls ≡ ε in G^(M));
//   * ψ∘emb_M ≡ id ⟹ emb_M injective.
//
// This module: §A generic tools (word-power embedding + the ≡-identity-on-generators master lemma),
// then §B the G^(M)-specific per-generator facts, then §C the wrap-identity + retraction assembly.
// ===========================================================================

// ===========================================================================
// §A — generic, reusable tools.
// ===========================================================================

/// `apply_embedding` distributes over `word_power`:  `emb(wⁱ) = (emb(w))ⁱ`.  (Analog of the
/// `symbol_power` version `lemma_apply_embedding_symbol_power`, for whole-word powers.)
pub proof fn lemma_apply_embedding_word_power(emb: Seq<Word>, w: Word, i: nat)
    ensures
        apply_embedding(emb, word_power(w, i)) =~= word_power(apply_embedding(emb, w), i),
    decreases i,
{
    if i == 0 {
        assert(word_power(w, 0) =~= empty_word());
        assert(apply_embedding(emb, empty_word()) =~= empty_word());
        assert(word_power(apply_embedding(emb, w), 0) =~= empty_word());
    } else {
        let k = (i - 1) as nat;
        assert(word_power(w, i) =~= w + word_power(w, k));
        lemma_apply_embedding_concat(emb, w, word_power(w, k));
        lemma_apply_embedding_word_power(emb, w, k);   // IH
        assert(word_power(apply_embedding(emb, w), i)
            =~= apply_embedding(emb, w) + word_power(apply_embedding(emb, w), k));
    }
}

/// **The ≡-identity-on-generators master lemma (G1).**  If an embedding `emb` sends every generator
/// `Gen(g)` to a word equivalent to `[Gen(g)]` in `p` (and the images are valid), then `emb` acts as
/// the identity on the equivalence classes:  `apply_embedding(emb, w) ≡ w` for every valid word `w`.
/// This is the engine behind both "ψ∘emb ≡ id" (the retraction) and the `b ↦ tat⁻¹` substitution.
pub proof fn lemma_emb_id_on_gens_preserves(p: Presentation, emb: Seq<Word>, w: Word)
    requires
        presentation_valid(p),
        emb.len() == p.num_generators,
        forall|g: int| 0 <= g < p.num_generators ==> word_valid(#[trigger] emb[g], p.num_generators),
        forall|g: int| 0 <= g < p.num_generators ==>
            equiv_in_presentation(p, #[trigger] emb[g], seq![Symbol::Gen(g as nat)]),
        word_valid(w, p.num_generators),
    ensures
        equiv_in_presentation(p, apply_embedding(emb, w), w),
    decreases w.len(),
{
    if w.len() == 0 {
        assert(apply_embedding(emb, w) =~= empty_word());
        assert(w =~= empty_word());
        lemma_equiv_refl(p, w);
    } else {
        let s = w.first();
        let rest = w.drop_first();
        assert(word_valid(rest, p.num_generators)) by {
            assert forall|k: int| 0 <= k < rest.len()
                implies symbol_valid(#[trigger] rest[k], p.num_generators) by {
                assert(rest[k] == w[k + 1]);
            }
        }
        let img_s = apply_embedding_symbol(emb, s);
        let ae_rest = apply_embedding(emb, rest);
        assert(apply_embedding(emb, w) =~= img_s + ae_rest);

        // IH:  ae_rest ≡ rest
        lemma_emb_id_on_gens_preserves(p, emb, rest);

        // symbol fact:  img_s ≡ seq![s]
        assert(symbol_valid(s, p.num_generators));
        match s {
            Symbol::Gen(g) => {
                assert(img_s == emb[g as int]);
                assert(0 <= g < p.num_generators);
                assert(equiv_in_presentation(p, emb[g as int], seq![Symbol::Gen(g)]));
                assert(seq![s] =~= seq![Symbol::Gen(g)]);
                assert(equiv_in_presentation(p, img_s, seq![s]));
            }
            Symbol::Inv(g) => {
                assert(img_s == inverse_word(emb[g as int]));
                assert(0 <= g < p.num_generators);
                assert(equiv_in_presentation(p, emb[g as int], seq![Symbol::Gen(g)]));
                lemma_equiv_inverse(p, emb[g as int], seq![Symbol::Gen(g)]);
                lemma_inverse_singleton(Symbol::Gen(g));
                assert(seq![Symbol::Gen(g)] =~= Seq::new(1, |_i: int| Symbol::Gen(g)));
                assert(inverse_word(seq![Symbol::Gen(g)]) =~= seq![Symbol::Inv(g)]);
                assert(seq![s] =~= seq![Symbol::Inv(g)]);
                assert(equiv_in_presentation(p, img_s, seq![s]));
            }
        }

        // concat congruence:  img_s+ae_rest ≡ img_s+rest ≡ [s]+rest =~= w
        lemma_equiv_concat_right(p, img_s, ae_rest, rest);
        lemma_equiv_concat_left(p, img_s, seq![s], rest);
        lemma_equiv_transitive(p, img_s + ae_rest, img_s + rest, seq![s] + rest);
        // seq![s]+rest =~= w  and  apply_embedding(emb,w) =~= img_s+ae_rest  bridge to the ensures.
        assert(seq![s] + rest =~= w);
        assert(equiv_in_presentation(p, img_s + ae_rest, w));
        assert(apply_embedding(emb, w) =~= img_s + ae_rest);
    }
}

/// **Reconjugation** (mirror of `lemma_deconj`):  `t · (t⁻¹ · w · t) · t⁻¹ ≡ w`.
pub proof fn lemma_reconj(p: Presentation, t_idx: nat, w: Word)
    ensures
        equiv_in_presentation(p,
            seq![Symbol::Gen(t_idx)]
                + (seq![Symbol::Inv(t_idx)] + w + seq![Symbol::Gen(t_idx)])
                + seq![Symbol::Inv(t_idx)],
            w),
{
    let gt = seq![Symbol::Gen(t_idx)];
    let it = seq![Symbol::Inv(t_idx)];
    let c = gt + it;   // t · t⁻¹
    lemma_inverse_singleton(Symbol::Gen(t_idx));
    assert(gt =~= Seq::new(1, |_i: int| Symbol::Gen(t_idx)));
    assert(inverse_word(gt) =~= it);
    lemma_word_inverse_right(p, gt);   // gt · inverse_word(gt) ≡ ε, i.e. c ≡ ε
    assert(gt + (it + w + gt) + it =~= (c + w) + c);
    // c + w ≡ ε + w =~= w
    lemma_equiv_concat_left(p, c, empty_word(), w);
    assert(empty_word() + w =~= w);
    // (c+w)+c ≡ w + c
    lemma_equiv_concat_left(p, c + w, w, c);
    // w + c ≡ w + ε =~= w
    lemma_equiv_concat_right(p, w, c, empty_word());
    assert(w + empty_word() =~= w);
    lemma_equiv_transitive(p, (c + w) + c, w + c, w);
}

// ===========================================================================
// §B — the G^(M)-specific per-generator facts (the content of the Tietze elimination).
//   G := hnn_presentation(miller_data(n, decls)),  num_generators = n+3,
//   a = Gen(n),  b = Gen(n+1),  t = Gen(n+2) (HNN stable).
// ===========================================================================

/// **`b ↦ tat⁻¹` recovery (R0).**  The base association `t⁻¹·b·t ≡ a` recovers `b ≡ b_sub = tat⁻¹`.
pub proof fn lemma_collapse_b_recovers(n: nat, decls: Seq<Word>)
    requires
        forall|k: int| 0 <= k < decls.len() ==> word_valid(#[trigger] decls[k], n),
    ensures
        equiv_in_presentation(hnn_presentation(miller_data(n, decls)),
            b_sub(n, (n + 2) as nat), seq![Symbol::Gen((n + 1) as nat)]),
{
    let data = miller_data(n, decls);
    let g = hnn_presentation(data);
    lemma_miller_data_valid(n, decls);
    lemma_hnn_presentation_valid(data);

    let gt = seq![Symbol::Gen((n + 2) as nat)];
    let it = seq![Symbol::Inv((n + 2) as nat)];
    let aa = seq![Symbol::Gen(n)];                 // a = Gen(n)   = b_col[0]
    let bb = seq![Symbol::Gen((n + 1) as nat)];    // b = Gen(n+1) = a_col[0]

    assert(data.base.num_generators == n + 2);
    assert(stable_letter(data) == Symbol::Gen((n + 2) as nat));
    assert(stable_letter_inv(data) == Symbol::Inv((n + 2) as nat));
    assert(data.associations[0].0 == a_col(n)[0]);
    assert(data.associations[0].1 == b_col(n)[0]);
    assert(a_col(n)[0] =~= bb);
    assert(b_col(n)[0] =~= aa);

    lemma_hnn_conjugation(data, 0);
    assert(Seq::new(1, |_j: int| stable_letter_inv(data)) =~= it);
    assert(Seq::new(1, |_j: int| stable_letter(data)) =~= gt);
    // hnn_conjugation ⟹  it + bb + gt ≡ aa
    assert(equiv_in_presentation(g, it + bb + gt, aa));

    // word_valid(it+bb+gt) for symmetric
    assert(word_valid(it + bb + gt, g.num_generators)) by {
        assert forall|k: int| 0 <= k < (it + bb + gt).len()
            implies symbol_valid(#[trigger] (it + bb + gt)[k], g.num_generators) by {}
    }
    lemma_equiv_symmetric(g, it + bb + gt, aa);    // aa ≡ it+bb+gt

    // b_sub = gt + aa + it ;  replace aa with (it+bb+gt), then reconj.
    lemma_equiv_concat_right(g, gt, aa, it + bb + gt);
    lemma_equiv_concat_left(g, gt + aa, gt + (it + bb + gt), it);
    lemma_reconj(g, (n + 2) as nat, bb);           // gt+(it+bb+gt)+it ≡ bb
    lemma_equiv_transitive(g, (gt + aa) + it, (gt + (it + bb + gt)) + it, bb);
    assert(b_sub(n, (n + 2) as nat) =~= (gt + aa) + it);
}

/// **`cⱼ`-association solved (Rj).**  `t⁻¹·acolⱼ·t ≡ bcolⱼ` solves to `acolⱼ ≡ t·bcolⱼ·t⁻¹`.
pub proof fn lemma_acol_as_conj(n: nat, decls: Seq<Word>, j: nat)
    requires
        forall|k: int| 0 <= k < decls.len() ==> word_valid(#[trigger] decls[k], n),
        j < n,
    ensures
        equiv_in_presentation(hnn_presentation(miller_data(n, decls)),
            acol_elt(n, j), conj_t((n + 2) as nat, bcol_elt(n, j))),
{
    let data = miller_data(n, decls);
    let g = hnn_presentation(data);
    lemma_miller_data_valid(n, decls);
    lemma_hnn_presentation_valid(data);

    let gt = seq![Symbol::Gen((n + 2) as nat)];
    let it = seq![Symbol::Inv((n + 2) as nat)];
    let ac = acol_elt(n, j);
    let bc = bcol_elt(n, j);

    assert(data.base.num_generators == n + 2);
    assert(stable_letter(data) == Symbol::Gen((n + 2) as nat));
    assert(stable_letter_inv(data) == Symbol::Inv((n + 2) as nat));
    assert(data.associations[(j + 1) as int].0 == a_col(n)[(j + 1) as int]);
    assert(data.associations[(j + 1) as int].1 == b_col(n)[(j + 1) as int]);
    assert(a_col(n)[(j + 1) as int] == ac);
    assert(b_col(n)[(j + 1) as int] == bc);

    lemma_hnn_conjugation(data, (j + 1) as int);
    assert(Seq::new(1, |_jj: int| stable_letter_inv(data)) =~= it);
    assert(Seq::new(1, |_jj: int| stable_letter(data)) =~= gt);
    // hnn_conjugation ⟹  it + ac + gt ≡ bc
    assert(equiv_in_presentation(g, it + ac + gt, bc));

    // conj both sides by t:  gt + (it+ac+gt) + it ≡ gt + bc + it = conj_t(t, bc)
    lemma_equiv_concat_right(g, gt, it + ac + gt, bc);
    lemma_equiv_concat_left(g, gt + (it + ac + gt), gt + bc, it);
    // reconj: gt+(it+ac+gt)+it ≡ ac
    lemma_reconj(g, (n + 2) as nat, ac);

    // ac ≡ (gt+(it+ac+gt))+it ≡ (gt+bc)+it = conj_t(t, bc)
    assert(word_valid((gt + (it + ac + gt)) + it, g.num_generators)) by {
        assert forall|k: int| 0 <= k < ((gt + (it + ac + gt)) + it).len()
            implies symbol_valid(#[trigger] ((gt + (it + ac + gt)) + it)[k], g.num_generators) by {}
    }
    lemma_equiv_symmetric(g, (gt + (it + ac + gt)) + it, ac);
    lemma_equiv_transitive(g, ac, (gt + (it + ac + gt)) + it, (gt + bc) + it);
    assert(conj_t((n + 2) as nat, bc) =~= (gt + bc) + it);
}

/// The `b ↦ tat⁻¹` substitution embedding on G^(M)'s gens:  identity except `b = Gen(n+1) ↦ b_sub`.
pub open spec fn beta_emb(n: nat) -> Seq<Word> {
    Seq::new((n + 3) as nat, |g: int|
        if g == (n + 1) as int { b_sub(n, (n + 2) as nat) }
        else { seq![Symbol::Gen(g as nat)] })
}

proof fn lemma_beta_emb_index(n: nat, g: int)
    requires
        0 <= g < n + 3,
    ensures
        beta_emb(n).len() == n + 3,
        g == (n + 1) as int ==> beta_emb(n)[g] == b_sub(n, (n + 2) as nat),
        g != (n + 1) as int ==> beta_emb(n)[g] == seq![Symbol::Gen(g as nat)],
{
}

/// **β ≡ identity** (G1 instance):  `apply_embedding(β, w) ≡ w` in G^(M).  Discharges `b ↦ tat⁻¹`.
pub proof fn lemma_beta_id(n: nat, decls: Seq<Word>, w: Word)
    requires
        forall|k: int| 0 <= k < decls.len() ==> word_valid(#[trigger] decls[k], n),
        word_valid(w, (n + 3) as nat),
    ensures
        equiv_in_presentation(hnn_presentation(miller_data(n, decls)),
            apply_embedding(beta_emb(n), w), w),
{
    let data = miller_data(n, decls);
    let g = hnn_presentation(data);
    let beta = beta_emb(n);
    lemma_miller_data_valid(n, decls);
    lemma_hnn_presentation_valid(data);
    assert(g.num_generators == n + 3);
    assert(beta.len() == n + 3);

    assert forall|gg: int| 0 <= gg < g.num_generators
        implies word_valid(#[trigger] beta[gg], g.num_generators) by {
        lemma_beta_emb_index(n, gg);
        assert forall|m: int| 0 <= m < beta[gg].len()
            implies symbol_valid(#[trigger] beta[gg][m], g.num_generators) by {}
    }
    lemma_collapse_b_recovers(n, decls);    // b_sub ≡ [Gen(n+1)]
    assert forall|gg: int| 0 <= gg < g.num_generators
        implies equiv_in_presentation(g, #[trigger] beta[gg], seq![Symbol::Gen(gg as nat)]) by {
        lemma_beta_emb_index(n, gg);
        if gg == (n + 1) as int {
            assert(beta[gg] == b_sub(n, (n + 2) as nat));
            assert(seq![Symbol::Gen(gg as nat)] =~= seq![Symbol::Gen((n + 1) as nat)]);
        } else {
            assert(beta[gg] == seq![Symbol::Gen(gg as nat)]);
            lemma_equiv_refl(g, seq![Symbol::Gen(gg as nat)]);
        }
    }
    lemma_emb_id_on_gens_preserves(g, beta, w);
}

/// `bcolⱼ` is a valid word over G^(M)'s `n+3` generators.
proof fn lemma_bcol_elt_valid(n: nat, j: nat)
    ensures
        word_valid(bcol_elt(n, j), (n + 3) as nat),
{
    let i = (j + 1) as nat;
    let q0 = symbol_power(Symbol::Inv((n + 1) as nat), i);
    let q1 = seq![Symbol::Gen(n)];
    let q2 = symbol_power(Symbol::Gen((n + 1) as nat), i);
    lemma_symbol_power_valid(Symbol::Inv((n + 1) as nat), i, (n + 3) as nat);
    lemma_symbol_power_valid(Symbol::Gen((n + 1) as nat), i, (n + 3) as nat);
    assert(word_valid(q1, (n + 3) as nat)) by {
        assert forall|m: int| 0 <= m < q1.len() implies symbol_valid(#[trigger] q1[m], (n + 3) as nat) by {}
    }
    lemma_concat_word_valid(q0, q1, (n + 3) as nat);
    lemma_concat_word_valid(q0 + q1, q2, (n + 3) as nat);
    assert(bcol_elt(n, j) =~= (q0 + q1) + q2);
}

/// **`col_img_b ≡ bcolⱼ`** — the composite emb's image of `b⁻ⁱabⁱ` equals it back (β-substitution).
pub proof fn lemma_col_img_b_eq_bcol(n: nat, decls: Seq<Word>, j: nat)
    requires
        forall|k: int| 0 <= k < decls.len() ==> word_valid(#[trigger] decls[k], n),
        j < n,
    ensures
        equiv_in_presentation(hnn_presentation(miller_data(n, decls)),
            col_img_b(n, n, (n + 2) as nat, (j + 1) as nat), bcol_elt(n, j)),
{
    let data = miller_data(n, decls);
    let g = hnn_presentation(data);
    let beta = beta_emb(n);
    let i = (j + 1) as nat;
    let bc = bcol_elt(n, j);

    // bc = q0 + q1 + q2
    let q0 = symbol_power(Symbol::Inv((n + 1) as nat), i);
    let q1 = seq![Symbol::Gen(n)];
    let q2 = symbol_power(Symbol::Gen((n + 1) as nat), i);
    assert(bc =~= (q0 + q1) + q2);

    lemma_apply_embedding_concat(beta, q0 + q1, q2);
    lemma_apply_embedding_concat(beta, q0, q1);
    lemma_beta_emb_index(n, (n + 1) as int);    // beta[n+1] = b_sub
    lemma_beta_emb_index(n, n as int);          // beta[n]   = [Gen(n)]
    lemma_emb_gen_power(beta, (n + 1) as nat, i);
    lemma_inverse_b_sub(n, (n + 2) as nat);     // inverse_word(b_sub) = binv_sub
    lemma_apply_embedding_singleton(beta, Symbol::Gen(n));

    // apply_embedding(beta, bc) =~= wp(binv_sub,i) + [Gen(n)] + wp(b_sub,i) =~= col_img_b
    lemma_ib_form(n, n, (n + 2) as nat, j);

    lemma_bcol_elt_valid(n, j);
    lemma_beta_id(n, decls, bc);                // apply_embedding(beta, bc) ≡ bc
}

/// Suffix cancellation:  `x·s ≡ y·s ⟹ x ≡ y`.
proof fn lemma_cancel_suffix(g: Presentation, x: Word, y: Word, suf: Word)
    requires
        presentation_valid(g),
        word_valid(x, g.num_generators),
        word_valid(y, g.num_generators),
        word_valid(suf, g.num_generators),
        equiv_in_presentation(g, x + suf, y + suf),
    ensures
        equiv_in_presentation(g, x, y),
{
    let iv = inverse_word(suf);
    lemma_right_cancel(g, x, suf);     // (x+suf)+iv ≡ x
    lemma_right_cancel(g, y, suf);     // (y+suf)+iv ≡ y
    lemma_equiv_concat_left(g, x + suf, y + suf, iv);   // (x+suf)+iv ≡ (y+suf)+iv
    lemma_inverse_word_valid(suf, g.num_generators);
    lemma_concat_word_valid(x + suf, iv, g.num_generators);
    lemma_concat_word_valid(x, suf, g.num_generators);
    lemma_equiv_symmetric(g, (x + suf) + iv, x);
    lemma_equiv_transitive(g, x, (x + suf) + iv, (y + suf) + iv);
    lemma_equiv_transitive(g, x, (y + suf) + iv, y);
}

/// **THE c-GENERATOR CRUX (Pc).**  `mcw(j,n,n+2) ≡ Gen(j)` in G^(M) — i.e. the collapse image of `cⱼ`
/// is recovered as `cⱼ` itself (the `cⱼ ↦ uⱼ(a,t)` Tietze elimination, reversed).
pub proof fn lemma_mcw_recovers_c(n: nat, decls: Seq<Word>, j: nat)
    requires
        forall|k: int| 0 <= k < decls.len() ==> word_valid(#[trigger] decls[k], n),
        j < n,
    ensures
        equiv_in_presentation(hnn_presentation(miller_data(n, decls)),
            miller_collapse_word(j, n, (n + 2) as nat), seq![Symbol::Gen(j)]),
{
    let data = miller_data(n, decls);
    let g = hnn_presentation(data);
    lemma_miller_data_valid(n, decls);
    lemma_hnn_presentation_valid(data);
    assert(g.num_generators == n + 3);

    let i = (j + 1) as nat;
    let gt = seq![Symbol::Gen((n + 2) as nat)];
    let it = seq![Symbol::Inv((n + 2) as nat)];
    let mcw = miller_collapse_word(j, n, (n + 2) as nat);
    let am = symbol_power(Symbol::Inv(n), i);
    let ap = symbol_power(Symbol::Gen(n), i);
    let bsub = b_sub(n, (n + 2) as nat);
    let gj = seq![Symbol::Gen(j)];
    let bb = seq![Symbol::Gen((n + 1) as nat)];
    let cia = col_img_a(n, n, (n + 2) as nat, i);
    let cib = col_img_b(n, n, (n + 2) as nat, i);
    let ac = acol_elt(n, j);
    let bc = bcol_elt(n, j);

    // (1) cia ≡ conj_t(t, cib)            [lemma_ia_conj, structural]
    lemma_ia_conj(g, n, n, (n + 2) as nat, j);
    // (2) cib ≡ bc                        [β-substitution]
    lemma_col_img_b_eq_bcol(n, decls, j);
    // conj_t(t, cib) ≡ conj_t(t, bc)
    lemma_equiv_concat_right(g, gt, cib, bc);
    lemma_equiv_concat_left(g, gt + cib, gt + bc, it);
    assert(conj_t((n + 2) as nat, cib) =~= (gt + cib) + it);
    assert(conj_t((n + 2) as nat, bc) =~= (gt + bc) + it);
    // (3) ac ≡ conj_t(t, bc)              [Rj]
    lemma_acol_as_conj(n, decls, j);
    // chain: cia ≡ conj_t(t,cib) ≡ conj_t(t,bc) ≡ ac  (use symmetric on (3))
    // word_valids for symmetric
    assert(word_valid(conj_t((n + 2) as nat, bc), g.num_generators)) by {
        lemma_acol_elt_valid_local(n, j);   // ac valid ⟹ via Rj equiv only need conj valid; build directly
    }
    lemma_equiv_transitive(g, cia, conj_t((n + 2) as nat, cib), conj_t((n + 2) as nat, bc));
    lemma_equiv_symmetric(g, ac, conj_t((n + 2) as nat, bc));
    lemma_equiv_transitive(g, cia, conj_t((n + 2) as nat, bc), ac);

    // (4) cia =~= ((mcw+am)+bsub)+ap      [lemma_ia_form]
    lemma_ia_form(n, n, (n + 2) as nat, j);
    // so ((mcw+am)+bsub)+ap ≡ ac
    // ac =~= (([Gen(j)]+am)+bb)+ap
    assert(ac =~= ((gj + am) + bb) + ap);

    // peel ap:  ((mcw+am)+bsub) ≡ (([Gen(j)]+am)+bb)
    lemma_mcw_valid_local(n, j);                // mcw valid in n+3
    lemma_word_powers_valid_local(n, i);        // am, ap valid; bsub valid
    assert(word_valid((mcw + am) + bsub, g.num_generators)) by {
        lemma_concat_word_valid(mcw, am, g.num_generators);
        lemma_concat_word_valid(mcw + am, bsub, g.num_generators);
    }
    assert(word_valid((gj + am) + bb, g.num_generators)) by {
        assert(word_valid(gj, g.num_generators)) by {
            assert forall|m: int| 0 <= m < gj.len() implies symbol_valid(#[trigger] gj[m], g.num_generators) by {}
        }
        assert(word_valid(bb, g.num_generators)) by {
            assert forall|m: int| 0 <= m < bb.len() implies symbol_valid(#[trigger] bb[m], g.num_generators) by {}
        }
        lemma_concat_word_valid(gj, am, g.num_generators);
        lemma_concat_word_valid(gj + am, bb, g.num_generators);
    }
    // bridge cia and ac to the +-forms, then cancel_suffix(ap)
    assert(equiv_in_presentation(g, ((mcw + am) + bsub) + ap, ((gj + am) + bb) + ap));
    lemma_cancel_suffix(g, (mcw + am) + bsub, (gj + am) + bb, ap);

    // convert bsub → bb:  (mcw+am)+bsub ≡ (mcw+am)+bb
    lemma_collapse_b_recovers(n, decls);        // bsub ≡ bb
    lemma_equiv_concat_right(g, mcw + am, bsub, bb);
    // (mcw+am)+bb ≡ (gj+am)+bb  via the peeled equiv + symmetric/transitive
    assert(word_valid(mcw + am, g.num_generators)) by {
        lemma_concat_word_valid(mcw, am, g.num_generators);
    }
    lemma_equiv_symmetric(g, (mcw + am) + bsub, (mcw + am) + bb);
    lemma_equiv_transitive(g, (mcw + am) + bb, (mcw + am) + bsub, (gj + am) + bb);

    // peel bb:  (mcw+am) ≡ (gj+am)
    assert(word_valid(bb, g.num_generators)) by {
        assert forall|m: int| 0 <= m < bb.len() implies symbol_valid(#[trigger] bb[m], g.num_generators) by {}
    }
    assert(word_valid(gj + am, g.num_generators)) by {
        assert(word_valid(gj, g.num_generators)) by {
            assert forall|m: int| 0 <= m < gj.len() implies symbol_valid(#[trigger] gj[m], g.num_generators) by {}
        }
        lemma_concat_word_valid(gj, am, g.num_generators);
    }
    lemma_cancel_suffix(g, mcw + am, gj + am, bb);

    // peel am:  mcw ≡ gj
    assert(word_valid(am, g.num_generators)) by {
        lemma_symbol_power_valid(Symbol::Inv(n), i, g.num_generators);
    }
    assert(word_valid(gj, g.num_generators)) by {
        assert forall|m: int| 0 <= m < gj.len() implies symbol_valid(#[trigger] gj[m], g.num_generators) by {}
    }
    lemma_cancel_suffix(g, mcw, gj, am);
}

/// `acolⱼ` valid in `n+3` (local helper).
proof fn lemma_acol_elt_valid_local(n: nat, j: nat)
    requires j < n,
    ensures word_valid(acol_elt(n, j), (n + 3) as nat),
{
    let i = (j + 1) as nat;
    let p0 = seq![Symbol::Gen(j)];
    let p1 = symbol_power(Symbol::Inv(n), i);
    let p2 = seq![Symbol::Gen((n + 1) as nat)];
    let p3 = symbol_power(Symbol::Gen(n), i);
    assert(word_valid(p0, (n + 3) as nat)) by {
        assert forall|m: int| 0 <= m < p0.len() implies symbol_valid(#[trigger] p0[m], (n + 3) as nat) by {}
    }
    assert(word_valid(p2, (n + 3) as nat)) by {
        assert forall|m: int| 0 <= m < p2.len() implies symbol_valid(#[trigger] p2[m], (n + 3) as nat) by {}
    }
    lemma_symbol_power_valid(Symbol::Inv(n), i, (n + 3) as nat);
    lemma_symbol_power_valid(Symbol::Gen(n), i, (n + 3) as nat);
    lemma_concat_word_valid(p0, p1, (n + 3) as nat);
    lemma_concat_word_valid(p0 + p1, p2, (n + 3) as nat);
    lemma_concat_word_valid((p0 + p1) + p2, p3, (n + 3) as nat);
    assert(acol_elt(n, j) =~= ((p0 + p1) + p2) + p3);
}

/// `mcw(j,n,n+2)` valid in `n+3` (local helper).
proof fn lemma_mcw_valid_local(n: nat, j: nat)
    ensures word_valid(miller_collapse_word(j, n, (n + 2) as nat), (n + 3) as nat),
{
    lemma_miller_collapse_word_valid(j, n, (n + 2) as nat, (n + 3) as nat);
}

/// `am = a⁻ⁱ`, `ap = aⁱ`, `bsub` valid in `n+3` (local helper).
proof fn lemma_word_powers_valid_local(n: nat, i: nat)
    ensures
        word_valid(symbol_power(Symbol::Inv(n), i), (n + 3) as nat),
        word_valid(symbol_power(Symbol::Gen(n), i), (n + 3) as nat),
        word_valid(b_sub(n, (n + 2) as nat), (n + 3) as nat),
{
    lemma_symbol_power_valid(Symbol::Inv(n), i, (n + 3) as nat);
    lemma_symbol_power_valid(Symbol::Gen(n), i, (n + 3) as nat);
    assert forall|m: int| 0 <= m < b_sub(n, (n + 2) as nat).len()
        implies symbol_valid(#[trigger] b_sub(n, (n + 2) as nat)[m], (n + 3) as nat) by {}
}

} // verus!
