use vstd::prelude::*;
use crate::symbol::*;
use crate::word::*;
use crate::presentation::*;
use crate::presentation_lemmas::{lemma_equiv_concat_left, lemma_equiv_concat_right,
    lemma_word_inverse_right};
use crate::benign::{apply_embedding, apply_embedding_symbol, lemma_apply_embedding_concat};
use crate::machine_group::word_power;
use crate::higman_consequences::lemma_equiv_inverse;
use crate::hnn::{hnn_presentation, stable_letter, stable_letter_inv, lemma_hnn_conjugation};
use crate::cohen_layer05::{a_col, b_col, acol_elt, bcol_elt, miller_data, lemma_miller_data_valid};
use crate::miller_collapse::{b_sub, binv_sub, miller_collapse_word, lemma_miller_collapse_word_valid};
use crate::miller_collapse_assoc::conj_t;
use crate::miller_collapse_reln::{col_img_a, col_img_b, lemma_ia_form, lemma_ia_conj, lemma_ib_form};
use crate::miller_collapse_eval::{lemma_emb_gen_power, lemma_apply_embedding_singleton,
    lemma_inverse_b_sub};
use crate::machine_group::{symbol_power, lemma_symbol_power_valid, lemma_word_valid_mono};
use crate::normal_form_afp_textbook::lemma_right_cancel;
use crate::britton_infra::lemma_hnn_presentation_valid;
use crate::miller_collapse::{miller_collapse_emb, lemma_miller_collapse_emb_len,
    lemma_miller_collapse_emb_valid};
use crate::miller_collapse_eval::{lemma_emb_head, lemma_emb_a, lemma_emb_b, lemma_emb_t,
    lemma_word_power_singleton};
use crate::miller_collapse_preserve::{k_m, dbar, lemma_k_m_valid, lemma_source_relators_struct};
use crate::h3_ii::{compose_embeddings, lemma_apply_embedding_compose};
use crate::homomorphism::{HomomorphismData, apply_hom, is_valid_homomorphism,
    lemma_hom_preserves_equiv, lemma_apply_hom_word_valid};
use crate::free_basis::lemma_apply_hom_eq_embedding;
use crate::presentation_lemmas::lemma_relator_is_identity;
use crate::benign::{embedding_injective, lemma_apply_embedding_valid};

verus! {

// ===========================================================================
// GAP-1 §9.2-item-(2) — `embedding_injective` (the faithfulness "boss fight").
//
// `docs/final-gate-axiom-removal-plan.md` §12.  Goal: the collapse `emb_M : G^(M) → K_M = ⟨a,t|D̄_M⟩`
// is INJECTIVE — `K_M`-equiv of `emb_M`-images ⟹ `G^(M)`-equiv.  This is Miller Thm 4.1's
// **Tietze collapse is an isomorphism** (`docs/higman-embedding-blueprint.md` §"Build order" step 2,
// p.108: "b = tat⁻¹ and each cᵢ = uⱼ(a,t), so G is 2-generated by {a,t}; Tietze to ⟨a,t|D̄⟩").  The
// proof is the **mutually-inverse-homomorphisms** technique (`cohen-faithfulness-primary-source.md`
// §54: "Two mutually-inverse homomorphisms ⟹ isomorphism.  No Britton-peel.") — a SECTION/RETRACTION
// argument that needs NO freeness (the `conj_family`/§D-probe freeness is the SEPARATE `C₀ ↪ G`
// HNN-faithfulness, Layer 0.5, not this Tietze iso).
//
// Route (companion-validated, textbook-confirmed):
//   * ψ : K_M → G^(M),  a = Gen(0) ↦ Gen(n),  t = Gen(1) ↦ Gen(n+2)  (inclusion of the 2 gens);
//   * ψ∘emb_M, as an embedding on G^(M)'s OWN generators, is exactly `miller_collapse_emb(n,n,n+2)`
//     (the routing-neutral "wrap-in-place" instantiation a_idx=M, t_idx=M+2 — designed for this);
//   * `lemma_wrap_is_identity`: that composite ≡ identity in G^(M) (per-generator: a/t trivial,
//     b = tat⁻¹ from the base association, cⱼ = uⱼ from the j-th association solved + b-substitution);
//   * ψ is a valid hom (its only relators D̄_M = emb_M(decls) push back to decls ≡ ε in G^(M));
//   * ψ∘emb_M ≡ id ⟹ emb_M injective.
//
// This module: §A generic tools (word-power embedding + the ≡-identity-on-generators master lemma),
// then §B the G^(M)-specific per-generator facts, then §C the wrap-identity + retraction assembly.
// ===========================================================================

// ===========================================================================
// §A — generic, reusable tools.
// ===========================================================================

/// `apply_embedding` distributes over `word_power`:  `emb(wⁱ) = (emb(w))ⁱ`.  (Analog of the
/// `symbol_power` version `lemma_apply_embedding_symbol_power`, for whole-word powers.)
pub proof fn lemma_apply_embedding_word_power(emb: Seq<Word>, w: Word, i: nat)
    ensures
        apply_embedding(emb, word_power(w, i)) =~= word_power(apply_embedding(emb, w), i),
    decreases i,
{
    if i == 0 {
        assert(word_power(w, 0) =~= empty_word());
        assert(apply_embedding(emb, empty_word()) =~= empty_word());
        assert(word_power(apply_embedding(emb, w), 0) =~= empty_word());
    } else {
        let k = (i - 1) as nat;
        assert(word_power(w, i) =~= w + word_power(w, k));
        lemma_apply_embedding_concat(emb, w, word_power(w, k));
        lemma_apply_embedding_word_power(emb, w, k);   // IH
        assert(word_power(apply_embedding(emb, w), i)
            =~= apply_embedding(emb, w) + word_power(apply_embedding(emb, w), k));
    }
}

/// **The ≡-identity-on-generators master lemma (G1).**  If an embedding `emb` sends every generator
/// `Gen(g)` to a word equivalent to `[Gen(g)]` in `p` (and the images are valid), then `emb` acts as
/// the identity on the equivalence classes:  `apply_embedding(emb, w) ≡ w` for every valid word `w`.
/// This is the engine behind both "ψ∘emb ≡ id" (the retraction) and the `b ↦ tat⁻¹` substitution.
pub proof fn lemma_emb_id_on_gens_preserves(p: Presentation, emb: Seq<Word>, w: Word)
    requires
        presentation_valid(p),
        emb.len() == p.num_generators,
        forall|g: int| 0 <= g < p.num_generators ==> word_valid(#[trigger] emb[g], p.num_generators),
        forall|g: int| 0 <= g < p.num_generators ==>
            equiv_in_presentation(p, #[trigger] emb[g], seq![Symbol::Gen(g as nat)]),
        word_valid(w, p.num_generators),
    ensures
        equiv_in_presentation(p, apply_embedding(emb, w), w),
    decreases w.len(),
{
    if w.len() == 0 {
        assert(apply_embedding(emb, w) =~= empty_word());
        assert(w =~= empty_word());
        lemma_equiv_refl(p, w);
    } else {
        let s = w.first();
        let rest = w.drop_first();
        assert(word_valid(rest, p.num_generators)) by {
            assert forall|k: int| 0 <= k < rest.len()
                implies symbol_valid(#[trigger] rest[k], p.num_generators) by {
                assert(rest[k] == w[k + 1]);
            }
        }
        let img_s = apply_embedding_symbol(emb, s);
        let ae_rest = apply_embedding(emb, rest);
        assert(apply_embedding(emb, w) =~= img_s + ae_rest);

        // IH:  ae_rest ≡ rest
        lemma_emb_id_on_gens_preserves(p, emb, rest);

        // symbol fact:  img_s ≡ seq![s]
        assert(symbol_valid(s, p.num_generators));
        match s {
            Symbol::Gen(g) => {
                assert(img_s == emb[g as int]);
                assert(0 <= g < p.num_generators);
                assert(equiv_in_presentation(p, emb[g as int], seq![Symbol::Gen(g)]));
                assert(seq![s] =~= seq![Symbol::Gen(g)]);
                assert(equiv_in_presentation(p, img_s, seq![s]));
            }
            Symbol::Inv(g) => {
                assert(img_s == inverse_word(emb[g as int]));
                assert(0 <= g < p.num_generators);
                assert(equiv_in_presentation(p, emb[g as int], seq![Symbol::Gen(g)]));
                lemma_equiv_inverse(p, emb[g as int], seq![Symbol::Gen(g)]);
                lemma_inverse_singleton(Symbol::Gen(g));
                assert(seq![Symbol::Gen(g)] =~= Seq::new(1, |_i: int| Symbol::Gen(g)));
                assert(inverse_word(seq![Symbol::Gen(g)]) =~= seq![Symbol::Inv(g)]);
                assert(seq![s] =~= seq![Symbol::Inv(g)]);
                assert(equiv_in_presentation(p, img_s, seq![s]));
            }
        }

        // concat congruence:  img_s+ae_rest ≡ img_s+rest ≡ [s]+rest =~= w
        lemma_equiv_concat_right(p, img_s, ae_rest, rest);
        lemma_equiv_concat_left(p, img_s, seq![s], rest);
        lemma_equiv_transitive(p, img_s + ae_rest, img_s + rest, seq![s] + rest);
        // seq![s]+rest =~= w  and  apply_embedding(emb,w) =~= img_s+ae_rest  bridge to the ensures.
        assert(seq![s] + rest =~= w);
        assert(equiv_in_presentation(p, img_s + ae_rest, w));
        assert(apply_embedding(emb, w) =~= img_s + ae_rest);
    }
}

/// **Reconjugation** (mirror of `lemma_deconj`):  `t · (t⁻¹ · w · t) · t⁻¹ ≡ w`.
pub proof fn lemma_reconj(p: Presentation, t_idx: nat, w: Word)
    ensures
        equiv_in_presentation(p,
            seq![Symbol::Gen(t_idx)]
                + (seq![Symbol::Inv(t_idx)] + w + seq![Symbol::Gen(t_idx)])
                + seq![Symbol::Inv(t_idx)],
            w),
{
    let gt = seq![Symbol::Gen(t_idx)];
    let it = seq![Symbol::Inv(t_idx)];
    let c = gt + it;   // t · t⁻¹
    lemma_inverse_singleton(Symbol::Gen(t_idx));
    assert(gt =~= Seq::new(1, |_i: int| Symbol::Gen(t_idx)));
    assert(inverse_word(gt) =~= it);
    lemma_word_inverse_right(p, gt);   // gt · inverse_word(gt) ≡ ε, i.e. c ≡ ε
    assert(gt + (it + w + gt) + it =~= (c + w) + c);
    // c + w ≡ ε + w =~= w
    lemma_equiv_concat_left(p, c, empty_word(), w);
    assert(empty_word() + w =~= w);
    // (c+w)+c ≡ w + c
    lemma_equiv_concat_left(p, c + w, w, c);
    // w + c ≡ w + ε =~= w
    lemma_equiv_concat_right(p, w, c, empty_word());
    assert(w + empty_word() =~= w);
    lemma_equiv_transitive(p, (c + w) + c, w + c, w);
}

// ===========================================================================
// §B — the G^(M)-specific per-generator facts (the content of the Tietze elimination).
//   G := hnn_presentation(miller_data(n, decls)),  num_generators = n+3,
//   a = Gen(n),  b = Gen(n+1),  t = Gen(n+2) (HNN stable).
// ===========================================================================

/// **`b ↦ tat⁻¹` recovery (R0).**  The base association `t⁻¹·b·t ≡ a` recovers `b ≡ b_sub = tat⁻¹`.
pub proof fn lemma_collapse_b_recovers(n: nat, decls: Seq<Word>)
    requires
        forall|k: int| 0 <= k < decls.len() ==> word_valid(#[trigger] decls[k], n),
    ensures
        equiv_in_presentation(hnn_presentation(miller_data(n, decls)),
            b_sub(n, (n + 2) as nat), seq![Symbol::Gen((n + 1) as nat)]),
{
    let data = miller_data(n, decls);
    let g = hnn_presentation(data);
    lemma_miller_data_valid(n, decls);
    lemma_hnn_presentation_valid(data);

    let gt = seq![Symbol::Gen((n + 2) as nat)];
    let it = seq![Symbol::Inv((n + 2) as nat)];
    let aa = seq![Symbol::Gen(n)];                 // a = Gen(n)   = b_col[0]
    let bb = seq![Symbol::Gen((n + 1) as nat)];    // b = Gen(n+1) = a_col[0]

    assert(data.base.num_generators == n + 2);
    assert(stable_letter(data) == Symbol::Gen((n + 2) as nat));
    assert(stable_letter_inv(data) == Symbol::Inv((n + 2) as nat));
    assert(data.associations[0].0 == a_col(n)[0]);
    assert(data.associations[0].1 == b_col(n)[0]);
    assert(a_col(n)[0] =~= bb);
    assert(b_col(n)[0] =~= aa);

    lemma_hnn_conjugation(data, 0);
    assert(Seq::new(1, |_j: int| stable_letter_inv(data)) =~= it);
    assert(Seq::new(1, |_j: int| stable_letter(data)) =~= gt);
    // hnn_conjugation ⟹  it + bb + gt ≡ aa
    assert(equiv_in_presentation(g, it + bb + gt, aa));

    // word_valid(it+bb+gt) for symmetric
    assert(word_valid(it + bb + gt, g.num_generators)) by {
        assert forall|k: int| 0 <= k < (it + bb + gt).len()
            implies symbol_valid(#[trigger] (it + bb + gt)[k], g.num_generators) by {}
    }
    lemma_equiv_symmetric(g, it + bb + gt, aa);    // aa ≡ it+bb+gt

    // b_sub = gt + aa + it ;  replace aa with (it+bb+gt), then reconj.
    lemma_equiv_concat_right(g, gt, aa, it + bb + gt);
    lemma_equiv_concat_left(g, gt + aa, gt + (it + bb + gt), it);
    lemma_reconj(g, (n + 2) as nat, bb);           // gt+(it+bb+gt)+it ≡ bb
    lemma_equiv_transitive(g, (gt + aa) + it, (gt + (it + bb + gt)) + it, bb);
    assert(b_sub(n, (n + 2) as nat) =~= (gt + aa) + it);
}

/// **`cⱼ`-association solved (Rj).**  `t⁻¹·acolⱼ·t ≡ bcolⱼ` solves to `acolⱼ ≡ t·bcolⱼ·t⁻¹`.
pub proof fn lemma_acol_as_conj(n: nat, decls: Seq<Word>, j: nat)
    requires
        forall|k: int| 0 <= k < decls.len() ==> word_valid(#[trigger] decls[k], n),
        j < n,
    ensures
        equiv_in_presentation(hnn_presentation(miller_data(n, decls)),
            acol_elt(n, j), conj_t((n + 2) as nat, bcol_elt(n, j))),
{
    let data = miller_data(n, decls);
    let g = hnn_presentation(data);
    lemma_miller_data_valid(n, decls);
    lemma_hnn_presentation_valid(data);

    let gt = seq![Symbol::Gen((n + 2) as nat)];
    let it = seq![Symbol::Inv((n + 2) as nat)];
    let ac = acol_elt(n, j);
    let bc = bcol_elt(n, j);

    assert(data.base.num_generators == n + 2);
    assert(stable_letter(data) == Symbol::Gen((n + 2) as nat));
    assert(stable_letter_inv(data) == Symbol::Inv((n + 2) as nat));
    assert(data.associations[(j + 1) as int].0 == a_col(n)[(j + 1) as int]);
    assert(data.associations[(j + 1) as int].1 == b_col(n)[(j + 1) as int]);
    assert(a_col(n)[(j + 1) as int] == ac);
    assert(b_col(n)[(j + 1) as int] == bc);

    lemma_hnn_conjugation(data, (j + 1) as int);
    assert(Seq::new(1, |_jj: int| stable_letter_inv(data)) =~= it);
    assert(Seq::new(1, |_jj: int| stable_letter(data)) =~= gt);
    // hnn_conjugation ⟹  it + ac + gt ≡ bc
    assert(equiv_in_presentation(g, it + ac + gt, bc));

    // conj both sides by t:  gt + (it+ac+gt) + it ≡ gt + bc + it = conj_t(t, bc)
    lemma_equiv_concat_right(g, gt, it + ac + gt, bc);
    lemma_equiv_concat_left(g, gt + (it + ac + gt), gt + bc, it);
    // reconj: gt+(it+ac+gt)+it ≡ ac
    lemma_reconj(g, (n + 2) as nat, ac);

    // ac ≡ (gt+(it+ac+gt))+it ≡ (gt+bc)+it = conj_t(t, bc)
    assert(word_valid((gt + (it + ac + gt)) + it, g.num_generators)) by {
        assert forall|k: int| 0 <= k < ((gt + (it + ac + gt)) + it).len()
            implies symbol_valid(#[trigger] ((gt + (it + ac + gt)) + it)[k], g.num_generators) by {}
    }
    lemma_equiv_symmetric(g, (gt + (it + ac + gt)) + it, ac);
    lemma_equiv_transitive(g, ac, (gt + (it + ac + gt)) + it, (gt + bc) + it);
    assert(conj_t((n + 2) as nat, bc) =~= (gt + bc) + it);
}

/// The `b ↦ tat⁻¹` substitution embedding on G^(M)'s gens:  identity except `b = Gen(n+1) ↦ b_sub`.
pub open spec fn beta_emb(n: nat) -> Seq<Word> {
    Seq::new((n + 3) as nat, |g: int|
        if g == (n + 1) as int { b_sub(n, (n + 2) as nat) }
        else { seq![Symbol::Gen(g as nat)] })
}

proof fn lemma_beta_emb_index(n: nat, g: int)
    requires
        0 <= g < n + 3,
    ensures
        beta_emb(n).len() == n + 3,
        g == (n + 1) as int ==> beta_emb(n)[g] == b_sub(n, (n + 2) as nat),
        g != (n + 1) as int ==> beta_emb(n)[g] == seq![Symbol::Gen(g as nat)],
{
}

/// **β ≡ identity** (G1 instance):  `apply_embedding(β, w) ≡ w` in G^(M).  Discharges `b ↦ tat⁻¹`.
pub proof fn lemma_beta_id(n: nat, decls: Seq<Word>, w: Word)
    requires
        forall|k: int| 0 <= k < decls.len() ==> word_valid(#[trigger] decls[k], n),
        word_valid(w, (n + 3) as nat),
    ensures
        equiv_in_presentation(hnn_presentation(miller_data(n, decls)),
            apply_embedding(beta_emb(n), w), w),
{
    let data = miller_data(n, decls);
    let g = hnn_presentation(data);
    let beta = beta_emb(n);
    lemma_miller_data_valid(n, decls);
    lemma_hnn_presentation_valid(data);
    assert(g.num_generators == n + 3);
    assert(beta.len() == n + 3);

    assert forall|gg: int| 0 <= gg < g.num_generators
        implies word_valid(#[trigger] beta[gg], g.num_generators) by {
        lemma_beta_emb_index(n, gg);
        assert forall|m: int| 0 <= m < beta[gg].len()
            implies symbol_valid(#[trigger] beta[gg][m], g.num_generators) by {}
    }
    lemma_collapse_b_recovers(n, decls);    // b_sub ≡ [Gen(n+1)]
    assert forall|gg: int| 0 <= gg < g.num_generators
        implies equiv_in_presentation(g, #[trigger] beta[gg], seq![Symbol::Gen(gg as nat)]) by {
        lemma_beta_emb_index(n, gg);
        if gg == (n + 1) as int {
            assert(beta[gg] == b_sub(n, (n + 2) as nat));
            assert(seq![Symbol::Gen(gg as nat)] =~= seq![Symbol::Gen((n + 1) as nat)]);
        } else {
            assert(beta[gg] == seq![Symbol::Gen(gg as nat)]);
            lemma_equiv_refl(g, seq![Symbol::Gen(gg as nat)]);
        }
    }
    lemma_emb_id_on_gens_preserves(g, beta, w);
}

/// `bcolⱼ` is a valid word over G^(M)'s `n+3` generators.
proof fn lemma_bcol_elt_valid(n: nat, j: nat)
    ensures
        word_valid(bcol_elt(n, j), (n + 3) as nat),
{
    let i = (j + 1) as nat;
    let q0 = symbol_power(Symbol::Inv((n + 1) as nat), i);
    let q1 = seq![Symbol::Gen(n)];
    let q2 = symbol_power(Symbol::Gen((n + 1) as nat), i);
    lemma_symbol_power_valid(Symbol::Inv((n + 1) as nat), i, (n + 3) as nat);
    lemma_symbol_power_valid(Symbol::Gen((n + 1) as nat), i, (n + 3) as nat);
    assert(word_valid(q1, (n + 3) as nat)) by {
        assert forall|m: int| 0 <= m < q1.len() implies symbol_valid(#[trigger] q1[m], (n + 3) as nat) by {}
    }
    lemma_concat_word_valid(q0, q1, (n + 3) as nat);
    lemma_concat_word_valid(q0 + q1, q2, (n + 3) as nat);
    assert(bcol_elt(n, j) =~= (q0 + q1) + q2);
}

/// **`col_img_b ≡ bcolⱼ`** — the composite emb's image of `b⁻ⁱabⁱ` equals it back (β-substitution).
pub proof fn lemma_col_img_b_eq_bcol(n: nat, decls: Seq<Word>, j: nat)
    requires
        forall|k: int| 0 <= k < decls.len() ==> word_valid(#[trigger] decls[k], n),
        j < n,
    ensures
        equiv_in_presentation(hnn_presentation(miller_data(n, decls)),
            col_img_b(n, n, (n + 2) as nat, (j + 1) as nat), bcol_elt(n, j)),
{
    let data = miller_data(n, decls);
    let g = hnn_presentation(data);
    let beta = beta_emb(n);
    let i = (j + 1) as nat;
    let bc = bcol_elt(n, j);

    // bc = q0 + q1 + q2
    let q0 = symbol_power(Symbol::Inv((n + 1) as nat), i);
    let q1 = seq![Symbol::Gen(n)];
    let q2 = symbol_power(Symbol::Gen((n + 1) as nat), i);
    assert(bc =~= (q0 + q1) + q2);

    lemma_apply_embedding_concat(beta, q0 + q1, q2);
    lemma_apply_embedding_concat(beta, q0, q1);
    lemma_beta_emb_index(n, (n + 1) as int);    // beta[n+1] = b_sub
    lemma_beta_emb_index(n, n as int);          // beta[n]   = [Gen(n)]
    lemma_emb_gen_power(beta, (n + 1) as nat, i);
    lemma_inverse_b_sub(n, (n + 2) as nat);     // inverse_word(b_sub) = binv_sub
    lemma_apply_embedding_singleton(beta, Symbol::Gen(n));

    // apply_embedding(beta, bc) =~= wp(binv_sub,i) + [Gen(n)] + wp(b_sub,i) =~= col_img_b
    lemma_ib_form(n, n, (n + 2) as nat, j);

    lemma_bcol_elt_valid(n, j);
    lemma_beta_id(n, decls, bc);                // apply_embedding(beta, bc) ≡ bc
}

/// Suffix cancellation:  `x·s ≡ y·s ⟹ x ≡ y`.
proof fn lemma_cancel_suffix(g: Presentation, x: Word, y: Word, suf: Word)
    requires
        presentation_valid(g),
        word_valid(x, g.num_generators),
        word_valid(y, g.num_generators),
        word_valid(suf, g.num_generators),
        equiv_in_presentation(g, x + suf, y + suf),
    ensures
        equiv_in_presentation(g, x, y),
{
    let iv = inverse_word(suf);
    lemma_right_cancel(g, x, suf);     // (x+suf)+iv ≡ x
    lemma_right_cancel(g, y, suf);     // (y+suf)+iv ≡ y
    lemma_equiv_concat_left(g, x + suf, y + suf, iv);   // (x+suf)+iv ≡ (y+suf)+iv
    lemma_inverse_word_valid(suf, g.num_generators);
    lemma_concat_word_valid(x + suf, iv, g.num_generators);
    lemma_concat_word_valid(x, suf, g.num_generators);
    lemma_equiv_symmetric(g, (x + suf) + iv, x);
    lemma_equiv_transitive(g, x, (x + suf) + iv, (y + suf) + iv);
    lemma_equiv_transitive(g, x, (y + suf) + iv, y);
}

/// **THE c-GENERATOR CRUX (Pc).**  `mcw(j,n,n+2) ≡ Gen(j)` in G^(M) — i.e. the collapse image of `cⱼ`
/// is recovered as `cⱼ` itself (the `cⱼ ↦ uⱼ(a,t)` Tietze elimination, reversed).
pub proof fn lemma_mcw_recovers_c(n: nat, decls: Seq<Word>, j: nat)
    requires
        forall|k: int| 0 <= k < decls.len() ==> word_valid(#[trigger] decls[k], n),
        j < n,
    ensures
        equiv_in_presentation(hnn_presentation(miller_data(n, decls)),
            miller_collapse_word(j, n, (n + 2) as nat), seq![Symbol::Gen(j)]),
{
    let data = miller_data(n, decls);
    let g = hnn_presentation(data);
    lemma_miller_data_valid(n, decls);
    lemma_hnn_presentation_valid(data);
    assert(g.num_generators == n + 3);

    let i = (j + 1) as nat;
    let gt = seq![Symbol::Gen((n + 2) as nat)];
    let it = seq![Symbol::Inv((n + 2) as nat)];
    let mcw = miller_collapse_word(j, n, (n + 2) as nat);
    let am = symbol_power(Symbol::Inv(n), i);
    let ap = symbol_power(Symbol::Gen(n), i);
    let bsub = b_sub(n, (n + 2) as nat);
    let gj = seq![Symbol::Gen(j)];
    let bb = seq![Symbol::Gen((n + 1) as nat)];
    let cia = col_img_a(n, n, (n + 2) as nat, i);
    let cib = col_img_b(n, n, (n + 2) as nat, i);
    let ac = acol_elt(n, j);
    let bc = bcol_elt(n, j);

    // (1) cia ≡ conj_t(t, cib)            [lemma_ia_conj, structural]
    lemma_ia_conj(g, n, n, (n + 2) as nat, j);
    // (2) cib ≡ bc                        [β-substitution]
    lemma_col_img_b_eq_bcol(n, decls, j);
    // conj_t(t, cib) ≡ conj_t(t, bc)
    lemma_equiv_concat_right(g, gt, cib, bc);
    lemma_equiv_concat_left(g, gt + cib, gt + bc, it);
    assert(conj_t((n + 2) as nat, cib) =~= (gt + cib) + it);
    assert(conj_t((n + 2) as nat, bc) =~= (gt + bc) + it);
    // (3) ac ≡ conj_t(t, bc)              [Rj]
    lemma_acol_as_conj(n, decls, j);
    // chain: cia ≡ conj_t(t,cib) ≡ conj_t(t,bc) ≡ ac  (use symmetric on (3))
    // word_valids for symmetric
    assert(word_valid(conj_t((n + 2) as nat, bc), g.num_generators)) by {
        lemma_acol_elt_valid_local(n, j);   // ac valid ⟹ via Rj equiv only need conj valid; build directly
    }
    lemma_equiv_transitive(g, cia, conj_t((n + 2) as nat, cib), conj_t((n + 2) as nat, bc));
    lemma_equiv_symmetric(g, ac, conj_t((n + 2) as nat, bc));
    lemma_equiv_transitive(g, cia, conj_t((n + 2) as nat, bc), ac);

    // (4) cia =~= ((mcw+am)+bsub)+ap      [lemma_ia_form]
    lemma_ia_form(n, n, (n + 2) as nat, j);
    // so ((mcw+am)+bsub)+ap ≡ ac
    // ac =~= (([Gen(j)]+am)+bb)+ap
    assert(ac =~= ((gj + am) + bb) + ap);

    // peel ap:  ((mcw+am)+bsub) ≡ (([Gen(j)]+am)+bb)
    lemma_mcw_valid_local(n, j);                // mcw valid in n+3
    lemma_word_powers_valid_local(n, i);        // am, ap valid; bsub valid
    assert(word_valid((mcw + am) + bsub, g.num_generators)) by {
        lemma_concat_word_valid(mcw, am, g.num_generators);
        lemma_concat_word_valid(mcw + am, bsub, g.num_generators);
    }
    assert(word_valid((gj + am) + bb, g.num_generators)) by {
        assert(word_valid(gj, g.num_generators)) by {
            assert forall|m: int| 0 <= m < gj.len() implies symbol_valid(#[trigger] gj[m], g.num_generators) by {}
        }
        assert(word_valid(bb, g.num_generators)) by {
            assert forall|m: int| 0 <= m < bb.len() implies symbol_valid(#[trigger] bb[m], g.num_generators) by {}
        }
        lemma_concat_word_valid(gj, am, g.num_generators);
        lemma_concat_word_valid(gj + am, bb, g.num_generators);
    }
    // bridge cia and ac to the +-forms, then cancel_suffix(ap)
    assert(equiv_in_presentation(g, ((mcw + am) + bsub) + ap, ((gj + am) + bb) + ap));
    lemma_cancel_suffix(g, (mcw + am) + bsub, (gj + am) + bb, ap);

    // convert bsub → bb:  (mcw+am)+bsub ≡ (mcw+am)+bb
    lemma_collapse_b_recovers(n, decls);        // bsub ≡ bb
    lemma_equiv_concat_right(g, mcw + am, bsub, bb);
    // (mcw+am)+bb ≡ (gj+am)+bb  via the peeled equiv + symmetric/transitive
    assert(word_valid(mcw + am, g.num_generators)) by {
        lemma_concat_word_valid(mcw, am, g.num_generators);
    }
    lemma_equiv_symmetric(g, (mcw + am) + bsub, (mcw + am) + bb);
    lemma_equiv_transitive(g, (mcw + am) + bb, (mcw + am) + bsub, (gj + am) + bb);

    // peel bb:  (mcw+am) ≡ (gj+am)
    assert(word_valid(bb, g.num_generators)) by {
        assert forall|m: int| 0 <= m < bb.len() implies symbol_valid(#[trigger] bb[m], g.num_generators) by {}
    }
    assert(word_valid(gj + am, g.num_generators)) by {
        assert(word_valid(gj, g.num_generators)) by {
            assert forall|m: int| 0 <= m < gj.len() implies symbol_valid(#[trigger] gj[m], g.num_generators) by {}
        }
        lemma_concat_word_valid(gj, am, g.num_generators);
    }
    lemma_cancel_suffix(g, mcw + am, gj + am, bb);

    // peel am:  mcw ≡ gj
    assert(word_valid(am, g.num_generators)) by {
        lemma_symbol_power_valid(Symbol::Inv(n), i, g.num_generators);
    }
    assert(word_valid(gj, g.num_generators)) by {
        assert forall|m: int| 0 <= m < gj.len() implies symbol_valid(#[trigger] gj[m], g.num_generators) by {}
    }
    lemma_cancel_suffix(g, mcw, gj, am);
}

/// `acolⱼ` valid in `n+3` (local helper).
proof fn lemma_acol_elt_valid_local(n: nat, j: nat)
    requires j < n,
    ensures word_valid(acol_elt(n, j), (n + 3) as nat),
{
    let i = (j + 1) as nat;
    let p0 = seq![Symbol::Gen(j)];
    let p1 = symbol_power(Symbol::Inv(n), i);
    let p2 = seq![Symbol::Gen((n + 1) as nat)];
    let p3 = symbol_power(Symbol::Gen(n), i);
    assert(word_valid(p0, (n + 3) as nat)) by {
        assert forall|m: int| 0 <= m < p0.len() implies symbol_valid(#[trigger] p0[m], (n + 3) as nat) by {}
    }
    assert(word_valid(p2, (n + 3) as nat)) by {
        assert forall|m: int| 0 <= m < p2.len() implies symbol_valid(#[trigger] p2[m], (n + 3) as nat) by {}
    }
    lemma_symbol_power_valid(Symbol::Inv(n), i, (n + 3) as nat);
    lemma_symbol_power_valid(Symbol::Gen(n), i, (n + 3) as nat);
    lemma_concat_word_valid(p0, p1, (n + 3) as nat);
    lemma_concat_word_valid(p0 + p1, p2, (n + 3) as nat);
    lemma_concat_word_valid((p0 + p1) + p2, p3, (n + 3) as nat);
    assert(acol_elt(n, j) =~= ((p0 + p1) + p2) + p3);
}

/// `mcw(j,n,n+2)` valid in `n+3` (local helper).
proof fn lemma_mcw_valid_local(n: nat, j: nat)
    ensures word_valid(miller_collapse_word(j, n, (n + 2) as nat), (n + 3) as nat),
{
    lemma_miller_collapse_word_valid(j, n, (n + 2) as nat, (n + 3) as nat);
}

/// `am = a⁻ⁱ`, `ap = aⁱ`, `bsub` valid in `n+3` (local helper).
proof fn lemma_word_powers_valid_local(n: nat, i: nat)
    ensures
        word_valid(symbol_power(Symbol::Inv(n), i), (n + 3) as nat),
        word_valid(symbol_power(Symbol::Gen(n), i), (n + 3) as nat),
        word_valid(b_sub(n, (n + 2) as nat), (n + 3) as nat),
{
    lemma_symbol_power_valid(Symbol::Inv(n), i, (n + 3) as nat);
    lemma_symbol_power_valid(Symbol::Gen(n), i, (n + 3) as nat);
    assert forall|m: int| 0 <= m < b_sub(n, (n + 2) as nat).len()
        implies symbol_valid(#[trigger] b_sub(n, (n + 2) as nat)[m], (n + 3) as nat) by {}
}

// ===========================================================================
// §C — the wrap-identity + retraction assembly.
// ===========================================================================

/// **THE WRAP-IDENTITY.**  The "wrap-in-place" composite `emb(n,n,n+2) = ψ∘emb_M`, as an embedding on
/// G^(M)'s OWN generators, acts as the identity on equivalence classes:
/// `apply_embedding(emb(n,n,n+2), w) ≡ w`.  Per-generator (G1): a/t reflexive, b via R0, cⱼ via the
/// c-crux `lemma_mcw_recovers_c`.
pub proof fn lemma_wrap_is_identity(n: nat, decls: Seq<Word>, w: Word)
    requires
        forall|k: int| 0 <= k < decls.len() ==> word_valid(#[trigger] decls[k], n),
        word_valid(w, (n + 3) as nat),
    ensures
        equiv_in_presentation(hnn_presentation(miller_data(n, decls)),
            apply_embedding(miller_collapse_emb(n, n, (n + 2) as nat), w), w),
{
    let data = miller_data(n, decls);
    let g = hnn_presentation(data);
    let wrap = miller_collapse_emb(n, n, (n + 2) as nat);
    lemma_miller_data_valid(n, decls);
    lemma_hnn_presentation_valid(data);
    assert(g.num_generators == n + 3);
    lemma_miller_collapse_emb_len(n, n, (n + 2) as nat);
    lemma_miller_collapse_emb_valid(n, n, (n + 2) as nat, (n + 3) as nat);
    lemma_collapse_b_recovers(n, decls);

    assert forall|gg: int| 0 <= gg < g.num_generators
        implies equiv_in_presentation(g, #[trigger] wrap[gg], seq![Symbol::Gen(gg as nat)]) by {
        if gg < n {
            lemma_emb_head(n, n, (n + 2) as nat, gg as nat);
            lemma_mcw_recovers_c(n, decls, gg as nat);
        } else if gg == n as int {
            lemma_emb_a(n, n, (n + 2) as nat);
            lemma_equiv_refl(g, seq![Symbol::Gen(n)]);
            assert(seq![Symbol::Gen(gg as nat)] =~= seq![Symbol::Gen(n)]);
        } else if gg == (n + 1) as int {
            lemma_emb_b(n, n, (n + 2) as nat);
            assert(seq![Symbol::Gen(gg as nat)] =~= seq![Symbol::Gen((n + 1) as nat)]);
        } else {
            lemma_emb_t(n, n, (n + 2) as nat);
            lemma_equiv_refl(g, seq![Symbol::Gen((n + 2) as nat)]);
            assert(seq![Symbol::Gen(gg as nat)] =~= seq![Symbol::Gen((n + 2) as nat)]);
        }
    }
    lemma_emb_id_on_gens_preserves(g, wrap, w);
}

/// The retraction `ψ`'s generator images:  `a = Gen(0) ↦ Gen(n)`,  `t = Gen(1) ↦ Gen(n+2)`.
pub open spec fn section_imgs(n: nat) -> Seq<Word> {
    seq![ seq![Symbol::Gen(n)], seq![Symbol::Gen((n + 2) as nat)] ]
}

/// `inverse_word([Gen(x)]) =~= [Inv(x)]` (singleton-inverse, bridged through the `Seq::new` form).
proof fn lemma_inv_gen(x: nat)
    ensures
        inverse_word(seq![Symbol::Gen(x)]) =~= seq![Symbol::Inv(x)],
{
    lemma_inverse_singleton(Symbol::Gen(x));
    assert(seq![Symbol::Gen(x)] =~= Seq::new(1, |_i: int| Symbol::Gen(x)));
    assert(Seq::new(1, |_i: int| inverse_symbol(Symbol::Gen(x))) =~= seq![Symbol::Inv(x)]);
}

/// Relabel of the collapsed `b`/`b⁻¹` under `ψ`:  `b_sub(0,1) ↦ b_sub(n,n+2)`, `binv_sub` likewise.
proof fn lemma_relabel_bt(n: nat)
    ensures
        apply_embedding(section_imgs(n), b_sub(0, 1)) =~= b_sub(n, (n + 2) as nat),
        apply_embedding(section_imgs(n), binv_sub(0, 1)) =~= binv_sub(n, (n + 2) as nat),
{
    let psi = section_imgs(n);
    reveal_with_fuel(apply_embedding, 4);
    assert(psi[0] == seq![Symbol::Gen(n)]);
    assert(psi[1] == seq![Symbol::Gen((n + 2) as nat)]);
    lemma_inv_gen((n + 2) as nat);    // inverse_word([Gen(n+2)]) =~= [Inv(n+2)]
    lemma_inv_gen(n);                 // inverse_word([Gen(n)])   =~= [Inv(n)]
}

/// **RELABEL_MCW.**  Applying `ψ` to `uⱼ(a=0,t=1)` gives `uⱼ(a=n,t=n+2)` (the index relabel that makes
/// `ψ∘emb_M = emb(n,n,n+2)`).
proof fn lemma_relabel_mcw(n: nat, k: nat)
    ensures
        apply_embedding(section_imgs(n), miller_collapse_word(k, 0, 1))
            =~= miller_collapse_word(k, n, (n + 2) as nat),
{
    let psi = section_imgs(n);
    let i = (k + 1) as nat;
    let p0 = seq![Symbol::Gen(1)];
    let p1 = word_power(binv_sub(0, 1), i);
    let p2 = seq![Symbol::Gen(0)];
    let p3 = word_power(b_sub(0, 1), i);
    let p4 = seq![Symbol::Inv(1)];
    let p5 = symbol_power(Symbol::Inv(0), i);
    let p6 = binv_sub(0, 1);
    let p7 = symbol_power(Symbol::Gen(0), i);

    // distribute apply_embedding over the 8-piece left-assoc concat
    lemma_apply_embedding_concat(psi, ((((((p0 + p1) + p2) + p3) + p4) + p5) + p6), p7);
    lemma_apply_embedding_concat(psi, (((((p0 + p1) + p2) + p3) + p4) + p5), p6);
    lemma_apply_embedding_concat(psi, ((((p0 + p1) + p2) + p3) + p4), p5);
    lemma_apply_embedding_concat(psi, (((p0 + p1) + p2) + p3), p4);
    lemma_apply_embedding_concat(psi, ((p0 + p1) + p2), p3);
    lemma_apply_embedding_concat(psi, (p0 + p1), p2);
    lemma_apply_embedding_concat(psi, p0, p1);

    // piece evaluations
    lemma_apply_embedding_singleton(psi, Symbol::Gen(1));   // p0 → [Gen(n+2)]
    lemma_apply_embedding_singleton(psi, Symbol::Gen(0));   // p2 → [Gen(n)]
    lemma_apply_embedding_singleton(psi, Symbol::Inv(1));   // p4 → [Inv(n+2)]
    lemma_inv_gen((n + 2) as nat);                         // inverse_word([Gen(n+2)]) = [Inv(n+2)]
    lemma_relabel_bt(n);                                    // ae(b_sub01)=b_sub, ae(binv_sub01)=binv_sub
    lemma_apply_embedding_word_power(psi, binv_sub(0, 1), i);   // p1 → wp(binv_sub(n,n+2),i)
    lemma_apply_embedding_word_power(psi, b_sub(0, 1), i);      // p3 → wp(b_sub(n,n+2),i)
    lemma_emb_gen_power(psi, 0, i);                            // p5, p7 (symbol-powers of Gen(0)/Inv(0))
    lemma_inv_gen(n);                                         // inverse_word([Gen(n)]) = [Inv(n)]
    lemma_word_power_singleton(Symbol::Inv(n), i);            // wp([Inv(n)],i)=symbol_power(Inv(n),i)
    lemma_word_power_singleton(Symbol::Gen(n), i);            // wp([Gen(n)],i)=symbol_power(Gen(n),i)

    // each evaluated piece equals the corresponding piece of mcw(k,n,n+2)
    let gt_n = seq![Symbol::Gen((n + 2) as nat)];
    let it_n = seq![Symbol::Inv((n + 2) as nat)];
    let ga_n = seq![Symbol::Gen(n)];
    assert(apply_embedding(psi, p0) =~= gt_n);
    assert(apply_embedding(psi, p1) =~= word_power(binv_sub(n, (n + 2) as nat), i));
    assert(apply_embedding(psi, p2) =~= ga_n);
    assert(apply_embedding(psi, p3) =~= word_power(b_sub(n, (n + 2) as nat), i));
    assert(apply_embedding(psi, p4) =~= it_n);
    assert(apply_embedding(psi, p5) =~= symbol_power(Symbol::Inv(n), i));
    assert(apply_embedding(psi, p6) =~= binv_sub(n, (n + 2) as nat));
    assert(apply_embedding(psi, p7) =~= symbol_power(Symbol::Gen(n), i));

    // assemble:  ae(p0)+...+ae(p7) =~= mcw(k,n,n+2)
    assert(miller_collapse_word(k, n, (n + 2) as nat) =~=
        ((((((apply_embedding(psi, p0) + apply_embedding(psi, p1)) + apply_embedding(psi, p2))
            + apply_embedding(psi, p3)) + apply_embedding(psi, p4)) + apply_embedding(psi, p5))
            + apply_embedding(psi, p6)) + apply_embedding(psi, p7));
}

/// **RELABEL.**  `ψ∘emb_M = emb(n,n,n+2)`  (the composite is the routing-neutral "wrap-in-place" emb).
proof fn lemma_section_compose(n: nat, decls: Seq<Word>)
    ensures
        compose_embeddings(section_imgs(n), miller_collapse_emb(n, 0, 1))
            =~= miller_collapse_emb(n, n, (n + 2) as nat),
{
    let psi = section_imgs(n);
    let emb_m = miller_collapse_emb(n, 0, 1);
    let wrap = miller_collapse_emb(n, n, (n + 2) as nat);
    let comp = compose_embeddings(psi, emb_m);
    lemma_miller_collapse_emb_len(n, 0, 1);
    lemma_miller_collapse_emb_len(n, n, (n + 2) as nat);
    assert(comp.len() == n + 3);
    assert forall|kk: int| 0 <= kk < comp.len() implies comp[kk] =~= wrap[kk] by {
        assert(comp[kk] == apply_embedding(psi, emb_m[kk]));
        if kk < n {
            lemma_emb_head(n, 0, 1, kk as nat);
            lemma_relabel_mcw(n, kk as nat);
            lemma_emb_head(n, n, (n + 2) as nat, kk as nat);
        } else if kk == n as int {
            lemma_emb_a(n, 0, 1);
            lemma_apply_embedding_singleton(psi, Symbol::Gen(0));
            lemma_emb_a(n, n, (n + 2) as nat);
        } else if kk == (n + 1) as int {
            lemma_emb_b(n, 0, 1);
            lemma_relabel_bt(n);
            lemma_emb_b(n, n, (n + 2) as nat);
        } else {
            lemma_emb_t(n, 0, 1);
            lemma_apply_embedding_singleton(psi, Symbol::Gen(1));
            lemma_emb_t(n, n, (n + 2) as nat);
        }
    }
}

/// The retraction homomorphism `ψ : K_M → G^(M)`,  `a ↦ Gen(n)`, `t ↦ Gen(n+2)`.
pub open spec fn section_hom(n: nat, decls: Seq<Word>) -> HomomorphismData {
    HomomorphismData {
        source: k_m(n, decls),
        target: hnn_presentation(miller_data(n, decls)),
        generator_images: section_imgs(n),
    }
}

/// **The composite identity:**  `ψ(emb_M(w)) ≡ w` in G^(M)  (the heart of the retraction).
pub proof fn lemma_collapse_section_id(n: nat, decls: Seq<Word>, w: Word)
    requires
        forall|k: int| 0 <= k < decls.len() ==> word_valid(#[trigger] decls[k], n),
        word_valid(w, (n + 3) as nat),
    ensures
        equiv_in_presentation(hnn_presentation(miller_data(n, decls)),
            apply_hom(section_hom(n, decls), apply_embedding(miller_collapse_emb(n, 0, 1), w)), w),
{
    let h = section_hom(n, decls);
    let emb_m = miller_collapse_emb(n, 0, 1);
    let u = apply_embedding(emb_m, w);
    lemma_apply_hom_eq_embedding(h, u);                  // apply_hom(h,u) =~= apply_embedding(section_imgs,u)
    lemma_miller_collapse_emb_len(n, 0, 1);              // emb_m.len() == n+3
    lemma_apply_embedding_compose(section_imgs(n), emb_m, w);  // = apply_embedding(compose, w)
    lemma_section_compose(n, decls);                    // compose =~= wrap
    lemma_wrap_is_identity(n, decls, w);                // apply_embedding(wrap, w) ≡ w
}

/// **ψ is a valid homomorphism.**  Its only relators `D̄_M = emb_M(decls)` push back to `decls ≡ ε`.
pub proof fn lemma_section_hom_valid(n: nat, decls: Seq<Word>)
    requires
        forall|k: int| 0 <= k < decls.len() ==> word_valid(#[trigger] decls[k], n),
    ensures
        is_valid_homomorphism(section_hom(n, decls)),
{
    let h = section_hom(n, decls);
    let data = miller_data(n, decls);
    let g = hnn_presentation(data);
    lemma_miller_data_valid(n, decls);
    lemma_hnn_presentation_valid(data);
    lemma_k_m_valid(n, decls);
    assert(g.num_generators == n + 3);
    assert(h.generator_images.len() == 2);
    assert(h.source.num_generators == 2);

    assert forall|ii: int| 0 <= ii < h.generator_images.len()
        implies word_valid(#[trigger] h.generator_images[ii], h.target.num_generators) by {
        assert forall|m: int| 0 <= m < h.generator_images[ii].len()
            implies symbol_valid(#[trigger] h.generator_images[ii][m], h.target.num_generators) by {}
    }

    lemma_source_relators_struct(n, decls);   // g.relators =~= decls + hnn_relators
    assert forall|ii: int| 0 <= ii < h.source.relators.len()
        implies equiv_in_presentation(h.target, apply_hom(h, h.source.relators[ii]), empty_word()) by {
        // h.source.relators = dbar(n,decls) ;  dbar[ii] = apply_embedding(emb_M, decls[ii])
        let r = h.source.relators[ii];
        assert(r == dbar(n, decls)[ii]);
        assert(r == apply_embedding(miller_collapse_emb(n, 0, 1), decls[ii]));
        assert(ii < decls.len());

        // apply_hom(h, r) ≡ decls[ii]  via the composite identity
        lemma_word_valid_mono(decls[ii], n, (n + 3) as nat);
        lemma_collapse_section_id(n, decls, decls[ii]);

        // decls[ii] ≡ ε  (it is g.relators[ii])
        lemma_relator_is_identity(g, ii);
        assert(g.relators[ii] == decls[ii]);
        lemma_equiv_transitive(g, apply_hom(h, r), decls[ii], empty_word());
    }
}

/// **★ THE BOSS FIGHT — `embedding_injective`.**  `K_M`-equiv of `emb_M`-images ⟹ `G^(M)`-equiv.
/// Miller Thm 4.1's Tietze collapse is an isomorphism, via the retraction `ψ` (`lemma_collapse_section_id`
/// + `lemma_section_hom_valid`).  No freeness — that is the SEPARATE `C₀ ↪ G` HNN-faithfulness (Layer 0.5).
pub proof fn lemma_collapse_injective(n: nat, decls: Seq<Word>)
    requires
        forall|k: int| 0 <= k < decls.len() ==> word_valid(#[trigger] decls[k], n),
    ensures
        embedding_injective(hnn_presentation(miller_data(n, decls)), k_m(n, decls),
            miller_collapse_emb(n, 0, 1)),
{
    let data = miller_data(n, decls);
    let g = hnn_presentation(data);
    let km = k_m(n, decls);
    let emb_m = miller_collapse_emb(n, 0, 1);
    let h = section_hom(n, decls);
    lemma_miller_data_valid(n, decls);
    lemma_hnn_presentation_valid(data);
    lemma_miller_collapse_emb_len(n, 0, 1);
    assert(g.num_generators == n + 3);
    assert(emb_m.len() == g.num_generators);
    lemma_section_hom_valid(n, decls);   // h valid (source = km = h.source)

    assert forall|w1: Word, w2: Word|
        word_valid(w1, g.num_generators) && word_valid(w2, g.num_generators)
        && equiv_in_presentation(km, apply_embedding(emb_m, w1), apply_embedding(emb_m, w2))
        implies #[trigger] equiv_in_presentation(g, w1, w2) by {
        // apply ψ:  equiv(g, ψ(emb_M(w1)), ψ(emb_M(w2)))
        lemma_hom_preserves_equiv(h, apply_embedding(emb_m, w1), apply_embedding(emb_m, w2));
        // ψ(emb_M(wi)) ≡ wi
        lemma_collapse_section_id(n, decls, w1);
        lemma_collapse_section_id(n, decls, w2);
        // word-validity of ψ(emb_M(w1)) for the symmetric step
        lemma_miller_collapse_emb_valid(n, 0, 1, 2);
        lemma_apply_embedding_valid(emb_m, w1, 2);          // emb_M(w1) valid in K_M (=2 gens)
        lemma_apply_hom_word_valid(h, apply_embedding(emb_m, w1));   // ψ-image valid in g
        // w1 ≡ ψ(emb_M(w1)) ≡ ψ(emb_M(w2)) ≡ w2
        lemma_equiv_symmetric(g, apply_hom(h, apply_embedding(emb_m, w1)), w1);
        lemma_equiv_transitive(g, w1, apply_hom(h, apply_embedding(emb_m, w1)),
            apply_hom(h, apply_embedding(emb_m, w2)));
        lemma_equiv_transitive(g, w1, apply_hom(h, apply_embedding(emb_m, w2)), w2);
    }
}

} // verus!
