use vstd::prelude::*;
use crate::symbol::*;
use crate::word::*;
use crate::pred_presentation::*;
use crate::pred_amalgamated_free_product::*;
//  Relator-agnostic helpers (pure word/seq ops) — REUSED verbatim from finite
//  benign.  (FA-8 will additionally reuse `is_left_word` / `unshift_sym` from
//  finite `normal_form_amalgamated` directly.)
use crate::benign::{factors_from_generators, concat_all, apply_embedding};

verus! {

//  ============================================================
//  FORK-A brick FA-7 — predicate-base amalgamated coset interface (2026-06-23).
//
//  The THIN interface layer of `normal_form_amalgamated.rs` over a predicate
//  base.  Scoping discovery (2026-06-23): the file britton actually consumes for
//  base-embeds is `normal_form_afp_textbook.rs` (the reduced-sequences /
//  shortlex injectivity), which imports from `normal_form_amalgamated` only the
//  SPEC FNS reproduced here — NOT the heavy Cayley/coset-table action machinery
//  (`h_act`, `valid_cayley`, `valid_phi`, `lemma_afp_injectivity` Cayley route,
//  ~70 relator sites).  That Cayley `lemma_afp_injectivity` is an ALTERNATE proof
//  off the critical path, so the predicate port LEAPFROGS it entirely — a large
//  scope reduction for Fork-A.
//
//  These are pure spec fns (relator-set-agnostic except for routing to
//  `equiv_in_pred_presentation`), so they type-swap verbatim from the finite
//  definitions.  `is_left_word` / `unshift_sym` are relator-agnostic ⟹ REUSED
//  from finite `normal_form_amalgamated`.  Kept separate (reversible, zero
//  regression).
//  ============================================================

///  The identifications define a valid subgroup isomorphism.  Predicate-base
///  analog of `identifications_isomorphic` (`normal_form_amalgamated.rs:28`).
pub open spec fn identifications_isomorphic_pred(data: PredAmalgamatedData) -> bool {
    let k = data.identifications.len();
    let a_words = Seq::new(k, |i: int| data.identifications[i].0);
    let b_words = Seq::new(k, |i: int| data.identifications[i].1);
    forall|w: Word| #![trigger word_valid(w, k as nat)] word_valid(w, k as nat) ==> (
        equiv_in_pred_presentation(data.p1, apply_embedding(a_words, w), empty_word())
        <==>
        equiv_in_pred_presentation(data.p2, apply_embedding(b_words, w), empty_word())
    )
}

///  A word `w` is in the subgroup of `p` generated by `gens`.  Predicate-base
///  analog of `benign::in_generated_subgroup`: `factors_from_generators` /
///  `concat_all` are relator-agnostic and reused; only the base-equivalence
///  goes predicate.
pub open spec fn in_generated_subgroup_pred(
    p: PredPresentation, gens: Seq<Word>, w: Word,
) -> bool {
    exists|factors: Seq<Word>|
        #[trigger] factors_from_generators(gens, factors) &&
        equiv_in_pred_presentation(p, concat_all(factors), w)
}

///  A word is in the left amalgamated subgroup A (generated by u_i words).
pub open spec fn in_left_subgroup_pred(data: PredAmalgamatedData, w: Word) -> bool {
    let k = data.identifications.len();
    let a_words = Seq::new(k, |i: int| data.identifications[i].0);
    in_generated_subgroup_pred(data.p1, a_words, w)
}

///  A word is in the right amalgamated subgroup B (generated by v_i words).
pub open spec fn in_right_subgroup_pred(data: PredAmalgamatedData, w: Word) -> bool {
    let k = data.identifications.len();
    let b_words = Seq::new(k, |i: int| data.identifications[i].1);
    in_generated_subgroup_pred(data.p2, b_words, w)
}

///  Two G₁-words are in the same A-coset: w₁⁻¹ · w₂ ∈ A.
pub open spec fn same_left_coset_pred(data: PredAmalgamatedData, w1: Word, w2: Word) -> bool {
    in_left_subgroup_pred(data, concat(inverse_word(w1), w2))
}

///  Two G₂-words are in the same B-coset.
pub open spec fn same_right_coset_pred(data: PredAmalgamatedData, w1: Word, w2: Word) -> bool {
    in_right_subgroup_pred(data, concat(inverse_word(w1), w2))
}

} //  verus!
