use vstd::prelude::*;
use crate::symbol::*;
use crate::word::*;
use crate::pred_presentation::*;
use crate::pred_presentation_lemmas::*;
use crate::benign::apply_embedding;

verus! {

//  ============================================================
//  FORK-A — predicate-base HNN extensions (2026-06-23).
//
//  This module is the predicate-base analog of `hnn.rs`, built over
//  `PredPresentation` (relators carried as a `spec_fn(Word) -> bool`) instead
//  of the finite `Presentation`.  It is the first real brick of the Fork-A
//  port that Cohen's faithfulness route needs (`docs/FORK-DECISION.md`,
//  `docs/cohen-faithfulness-primary-source.md` §1, §4): the H₃-level HNN
//  associations stay finite (`A/Aᵢ/A₊/A₋` are finitely generated), and the
//  ONLY thing that has to go predicate is the BASE relator set (= H₂'s
//  infinite family (II)).  Per primary-source §6c, the iso side-condition is
//  inherently finite and reduces entirely to base-equivalence, so the HNN
//  layer itself ports with no new ideas — exactly mirrored below.
//
//  Kept SEPARATE from the verified finite `hnn` module (zero regression risk;
//  reversible — delete the file + the `pub mod pred_hnn` line).  The hard
//  reverse base-embeds (Britton over a predicate base) is a LATER brick; this
//  module establishes the scaffold + the EASY forward embedding, which is
//  relator-set-agnostic and ports cleanly (primary-source §6a/§7c).
//
//  Mirrors `hnn.rs`:
//    * HNN presentation = base relators + the finite stable-letter relators,
//      so its predicate is `(base.relators)(w) || w ∈ {hnn_relator(data,i)}`.
//    * a base derivation step / derivation lifts to the HNN presentation
//      (the predicate is monotone: base relators imply HNN relators).
//  ============================================================

///  Data for a predicate-base HNN extension: a predicate base presentation
///  plus a FINITE sequence of association pairs.  Each pair (a_i, b_i)
///  represents the relation t⁻¹·a_i·t = b_i.
pub struct PredHNNData {
    pub base: PredPresentation,
    pub associations: Seq<(Word, Word)>,
}

///  The stable letter symbol: Gen(base.num_generators).
pub open spec fn stable_letter_pred(data: PredHNNData) -> Symbol {
    Symbol::Gen(data.base.num_generators)
}

///  The inverse of the stable letter.
pub open spec fn stable_letter_inv_pred(data: PredHNNData) -> Symbol {
    Symbol::Inv(data.base.num_generators)
}

///  Build the i-th HNN relator: t⁻¹ · a_i · t · b_i⁻¹.
pub open spec fn hnn_relator_pred(data: PredHNNData, i: int) -> Word
    recommends
        0 <= i < data.associations.len(),
{
    let (a_i, b_i) = data.associations[i];
    let t = stable_letter_pred(data);
    let t_inv = stable_letter_inv_pred(data);
    Seq::new(1, |_j: int| t_inv) + a_i + Seq::new(1, |_j: int| t) + inverse_word(b_i)
}

///  The extra (stable-letter) relators are a FINITE set, given as a membership
///  predicate: `w` is one of the `hnn_relator_pred(data, i)`.
pub open spec fn hnn_extra_relator_pred(data: PredHNNData, w: Word) -> bool {
    exists|i: int| 0 <= i < data.associations.len() && w == hnn_relator_pred(data, i)
}

///  The full HNN relator predicate: a base relator OR one of the finite HNN
///  relators.  This is the predicate-base analog of `base.relators ++
///  hnn_relators(data)` — the only structural difference vs `hnn.rs`.
pub open spec fn hnn_all_relator_pred(data: PredHNNData, w: Word) -> bool {
    (data.base.relators)(w) || hnn_extra_relator_pred(data, w)
}

///  The HNN presentation: base generators + t, base relators + HNN relators.
pub open spec fn hnn_pred_presentation(data: PredHNNData) -> PredPresentation {
    PredPresentation {
        num_generators: (data.base.num_generators + 1) as nat,
        relators: |w: Word| hnn_all_relator_pred(data, w),
    }
}

///  An HNN extension is valid when the base is valid and all association words
///  are word_valid over the base generators.
pub open spec fn hnn_pred_data_valid(data: PredHNNData) -> bool {
    pred_presentation_valid(data.base)
    && forall|i: int| #![trigger data.associations[i]] 0 <= i < data.associations.len() ==>
        word_valid(data.associations[i].0, data.base.num_generators)
        && word_valid(data.associations[i].1, data.base.num_generators)
}

///  The HNN associations define a valid isomorphism between the subgroups
///  generated by the a_i's and b_i's.  Mirror of `hnn_associations_isomorphic`
///  (`hnn.rs:74`) over the predicate base.  Note (primary-source §6c): the
///  quantifier ranges over the FINITE `k = associations.len()` generators and
///  reduces entirely to `equiv_in_pred_presentation(data.base, ·, ·)` — it is
///  well-formed precisely because the associations stay finite.
pub open spec fn hnn_pred_associations_isomorphic(data: PredHNNData) -> bool {
    let k = data.associations.len();
    let a_words = Seq::new(k, |i: int| data.associations[i].0);
    let b_words = Seq::new(k, |i: int| data.associations[i].1);
    forall|w: Word| #![trigger word_valid(w, k as nat)] word_valid(w, k as nat) ==> (
        equiv_in_pred_presentation(data.base, apply_embedding(a_words, w), empty_word())
        <==>
        equiv_in_pred_presentation(data.base, apply_embedding(b_words, w), empty_word())
    )
}

//  ============================================================
//  Small validity helpers (word/symbol validity is monotone in n).
//  ============================================================

///  symbol_valid is monotone: valid for n ⟹ valid for n+1.
pub proof fn lemma_symbol_valid_succ(s: Symbol, n: nat)
    requires
        symbol_valid(s, n),
    ensures
        symbol_valid(s, (n + 1) as nat),
{
}

///  word_valid is monotone: valid for n ⟹ valid for n+1.
pub proof fn lemma_word_valid_succ(w: Word, n: nat)
    requires
        word_valid(w, n),
    ensures
        word_valid(w, (n + 1) as nat),
{
    assert forall|i: int| 0 <= i < w.len() implies symbol_valid(#[trigger] w[i], (n + 1) as nat) by {
        assert(symbol_valid(w[i], n));
    }
}

///  A single-symbol word is valid for n iff the symbol is.
pub proof fn lemma_singleton_word_valid(s: Symbol, n: nat)
    requires
        symbol_valid(s, n),
    ensures
        word_valid(Seq::new(1, |_j: int| s), n),
{
    let w = Seq::new(1, |_j: int| s);
    assert forall|i: int| 0 <= i < w.len() implies symbol_valid(#[trigger] w[i], n) by {
        assert(w[i] == s);
    }
}

//  ============================================================
//  The HNN presentation is valid, and the base embeds (forward direction).
//  ============================================================

///  Applying the HNN relator predicate beta-reduces to `hnn_all_relator_pred`.
///  (Helper so callers can connect `(hnn_pred_presentation(data).relators)(w)`
///  to the named predicate.)
pub proof fn lemma_hnn_relators_unfold(data: PredHNNData, w: Word)
    ensures
        (hnn_pred_presentation(data).relators)(w) == hnn_all_relator_pred(data, w),
{
}

///  A base relator is an HNN relator (the predicate is monotone).
pub proof fn lemma_base_relator_in_hnn(data: PredHNNData, w: Word)
    requires
        (data.base.relators)(w),
    ensures
        (hnn_pred_presentation(data).relators)(w),
{
}

///  The HNN presentation is valid when the data is valid.
///  Port of the `presentation_valid(hp)` block inside `lemma_hnn_conjugation`
///  (`hnn.rs:240–285`), rephrased predicate-style (quantify over accepted
///  words instead of indexing).
pub proof fn lemma_hnn_pred_presentation_valid(data: PredHNNData)
    requires
        hnn_pred_data_valid(data),
    ensures
        pred_presentation_valid(hnn_pred_presentation(data)),
{
    reveal(pred_presentation_valid);
    let hp = hnn_pred_presentation(data);
    let ng = data.base.num_generators;
    let n = (ng + 1) as nat;
    assert(hp.num_generators == n);

    assert forall|w: Word| #![trigger (hp.relators)(w)] (hp.relators)(w) implies word_valid(w, n) by {
        //  (hp.relators)(w) == hnn_all_relator_pred(data, w)
        assert((hp.relators)(w) == hnn_all_relator_pred(data, w));
        if (data.base.relators)(w) {
            //  base relator: word_valid for ng, then monotone to n
            assert(word_valid(w, ng));
            lemma_word_valid_succ(w, ng);
        } else {
            //  one of the finite HNN relators
            assert(hnn_extra_relator_pred(data, w));
            let i = choose|i: int| 0 <= i < data.associations.len() && w == hnn_relator_pred(data, i);
            let (a_i, b_i) = data.associations[i];
            let t = stable_letter_pred(data);
            let t_inv = stable_letter_inv_pred(data);
            let t_w = Seq::new(1, |_j: int| t);
            let t_inv_w = Seq::new(1, |_j: int| t_inv);

            //  the stable letters are valid for n (index = ng < ng+1 = n)
            assert(symbol_valid(t, n));
            assert(symbol_valid(t_inv, n));
            lemma_singleton_word_valid(t, n);
            lemma_singleton_word_valid(t_inv, n);

            //  a_i, b_i valid for ng (from hnn_pred_data_valid), lift to n
            assert(word_valid(a_i, ng));
            assert(word_valid(b_i, ng));
            lemma_word_valid_succ(a_i, ng);
            lemma_word_valid_succ(b_i, ng);
            crate::word::lemma_inverse_word_valid(b_i, n);

            //  hr = t_inv_w + a_i + t_w + inverse_word(b_i)
            crate::word::lemma_concat_word_valid(t_inv_w, a_i, n);
            crate::word::lemma_concat_word_valid(t_inv_w + a_i, t_w, n);
            crate::word::lemma_concat_word_valid((t_inv_w + a_i) + t_w, inverse_word(b_i), n);
            assert(w == hnn_relator_pred(data, i));
            assert(w =~= ((t_inv_w + a_i) + t_w) + inverse_word(b_i));
        }
    }
}

///  A derivation step valid in the base is valid in the HNN presentation.
///  Port of `lemma_step_valid_in_hnn` (`hnn.rs:109`); even simpler here because
///  the relator predicate is monotone (base ⟹ HNN) rather than a Seq prefix.
pub proof fn lemma_step_valid_in_pred_hnn(
    data: PredHNNData,
    w: Word, step: PredDerivationStep, w_prime: Word,
)
    requires
        apply_step_pred(data.base, w, step) == Some(w_prime),
    ensures
        apply_step_pred(hnn_pred_presentation(data), w, step) == Some(w_prime),
{
    let hp = hnn_pred_presentation(data);
    let bp = data.base;
    match step {
        PredDerivationStep::FreeReduce { position } => {
            //  independent of relators / num_generators
        },
        PredDerivationStep::FreeExpand { position, symbol } => {
            //  guard held in base ⟹ symbol_valid(symbol, bp.num_generators);
            //  monotone to hp.num_generators = bp.num_generators + 1
            assert(symbol_valid(symbol, bp.num_generators));
            lemma_symbol_valid_succ(symbol, bp.num_generators);
            assert(symbol_valid(symbol, hp.num_generators));
        },
        PredDerivationStep::RelatorInsert { position, relator, inverted } => {
            //  guard held in base ⟹ (bp.relators)(relator) ⟹ (hp.relators)(relator)
            assert((bp.relators)(relator));
            assert(hnn_all_relator_pred(data, relator));
            assert((hp.relators)(relator));
        },
        PredDerivationStep::RelatorDelete { position, relator, inverted } => {
            assert((bp.relators)(relator));
            assert(hnn_all_relator_pred(data, relator));
            assert((hp.relators)(relator));
        },
    }
}

///  A derivation valid in the base is valid in the HNN presentation.
///  Port of `lemma_derivation_valid_in_hnn` (`hnn.rs:137`).
pub proof fn lemma_derivation_valid_in_pred_hnn(
    data: PredHNNData,
    steps: Seq<PredDerivationStep>, w1: Word, w2: Word,
)
    requires
        pred_derivation_produces(data.base, steps, w1) == Some(w2),
    ensures
        pred_derivation_produces(hnn_pred_presentation(data), steps, w1) == Some(w2),
    decreases steps.len(),
{
    if steps.len() == 0 {
    } else {
        let step = steps.first();
        let next = apply_step_pred(data.base, w1, step).unwrap();
        lemma_step_valid_in_pred_hnn(data, w1, step, next);
        lemma_derivation_valid_in_pred_hnn(data, steps.drop_first(), next, w2);
    }
}

///  Base group embeds (forward) in HNN extension:
///  if w1 ≡ w2 in base, then w1 ≡ w2 in hnn_pred_presentation.
///  Port of `lemma_base_embeds_in_hnn` (`hnn.rs:158`).  This is the EASY
///  direction (a base derivation IS an HNN derivation); the hard reverse
///  faithfulness (`britton_pred_embeds`) is a later brick.
pub proof fn lemma_base_embeds_in_pred_hnn(data: PredHNNData, w1: Word, w2: Word)
    requires
        equiv_in_pred_presentation(data.base, w1, w2),
    ensures
        equiv_in_pred_presentation(hnn_pred_presentation(data), w1, w2),
{
    let d = choose|d: PredDerivation| pred_derivation_valid(data.base, d, w1, w2);
    lemma_derivation_valid_in_pred_hnn(data, d.steps, w1, w2);
    let d_hnn = PredDerivation { steps: d.steps };
    assert(pred_derivation_valid(hnn_pred_presentation(data), d_hnn, w1, w2));
}

///  The HNN conjugation relation: t⁻¹·a_i·t ≡ b_i in the HNN presentation.
///  By construction t⁻¹·a_i·t·b_i⁻¹ is a relator, so it equals ε, hence
///  t⁻¹·a_i·t ≡ b_i.  Port of `lemma_hnn_conjugation` (`hnn.rs:173`), using
///  FA-1's validity lemma + FA-2's congruence algebra.
pub proof fn lemma_hnn_pred_conjugation(data: PredHNNData, i: int)
    requires
        0 <= i < data.associations.len(),
        hnn_pred_data_valid(data),
    ensures
        equiv_in_pred_presentation(
            hnn_pred_presentation(data),
            Seq::new(1, |_j: int| stable_letter_inv_pred(data))
                + data.associations[i].0
                + Seq::new(1, |_j: int| stable_letter_pred(data)),
            data.associations[i].1,
        ),
{
    let hp = hnn_pred_presentation(data);
    let ng = data.base.num_generators;
    let n = (ng + 1) as nat;
    let (a_i, b_i) = data.associations[i];
    let t = stable_letter_pred(data);
    let t_inv = stable_letter_inv_pred(data);
    let lhs = Seq::new(1, |_j: int| t_inv) + a_i + Seq::new(1, |_j: int| t);

    //  hp is valid (FA-1)
    lemma_hnn_pred_presentation_valid(data);

    //  relator ≡ ε (FA-2 word-carrying relator-is-identity)
    let relator = hnn_relator_pred(data, i);
    assert(hnn_extra_relator_pred(data, relator)) by {
        assert(0 <= i < data.associations.len() && relator == hnn_relator_pred(data, i));
    }
    assert((hp.relators)(relator));
    lemma_pred_relator_is_identity(hp, relator);

    assert(relator =~= concat(lhs, inverse_word(b_i)));

    //  concat(relator, b_i) ≡ b_i
    lemma_pred_equiv_concat_left(hp, relator, empty_word(), b_i);
    assert(concat(empty_word(), b_i) =~= b_i);
    lemma_pred_equiv_refl(hp, b_i);
    lemma_pred_equiv_transitive(hp, concat(relator, b_i), concat(empty_word(), b_i), b_i);

    assert(concat(relator, b_i) =~= concat(lhs, concat(inverse_word(b_i), b_i)));

    //  inv(b_i) · b_i ≡ ε
    lemma_pred_word_inverse_left(hp, b_i);

    //  lhs · (inv(b_i) · b_i) ≡ lhs · ε ≡ lhs
    lemma_pred_equiv_concat_right(hp, lhs, concat(inverse_word(b_i), b_i), empty_word());
    assert(concat(lhs, empty_word()) =~= lhs);
    lemma_pred_equiv_refl(hp, lhs);
    lemma_pred_equiv_transitive(hp, concat(lhs, concat(inverse_word(b_i), b_i)), concat(lhs, empty_word()), lhs);

    //  word_valid pieces for the symmetric call
    assert(word_valid(b_i, ng));
    lemma_word_valid_succ(b_i, ng);
    crate::word::lemma_inverse_word_valid(b_i, n);
    crate::word::lemma_concat_word_valid(inverse_word(b_i), b_i, n);

    assert(word_valid(a_i, ng));
    lemma_word_valid_succ(a_i, ng);
    assert(symbol_valid(t, n));
    assert(symbol_valid(t_inv, n));
    lemma_singleton_word_valid(t, n);
    lemma_singleton_word_valid(t_inv, n);
    let t_w = Seq::new(1, |_j: int| t);
    let t_inv_w = Seq::new(1, |_j: int| t_inv);
    crate::word::lemma_concat_word_valid(t_inv_w, a_i, n);
    crate::word::lemma_concat_word_valid(t_inv_w + a_i, t_w, n);
    assert(lhs =~= (t_inv_w + a_i) + t_w);
    assert(word_valid(lhs, n));
    crate::word::lemma_concat_word_valid(lhs, concat(inverse_word(b_i), b_i), n);

    //  symmetric: lhs ≡ concat(lhs, concat(inv(b_i), b_i))
    lemma_pred_equiv_symmetric(hp, concat(lhs, concat(inverse_word(b_i), b_i)), lhs);
    //  chain: lhs ≡ concat(relator, b_i) ≡ b_i
    lemma_pred_equiv_transitive(hp, lhs, concat(lhs, concat(inverse_word(b_i), b_i)), b_i);
}

} //  verus!
