//  ============================================================
//  E2.D — Property (vi) via the tower peel:  A ∩ ⟨T(M),rᵢ,lⱼ⟩ = T(M).
//  ============================================================
//  Own module (trigger isolation).  See docs/e2d-tower-peel-plan.md.
//
//  B(M) is a heterogeneous tower of single-letter HNN steps; every stable letter's associated
//  subgroup lives in the ORIGINAL base A.  We peel the tower top-down, reusing the verified
//  single-letter engine `lemma_property_ii` (kp_pinch, E2.C).
//
//  Ladder predicate `in_TMstable_upto(l)`: the subgroup of `b_m_upto(l)` generated by T(M)-gens +
//  the lower stable letters Gen(3+i), i<l.  Endpoints: level 0 = in_TM, level N = in_TMstable.
//  `lemma_vi_upto(l)`: downward induction; the φ-compatibility hypothesis of the engine is
//  discharged by the IH + property (v) (`prop_v_holds`).

use vstd::prelude::*;
use crate::symbol::*;
use crate::word::*;
use crate::presentation::*;
use crate::hnn::*;
use crate::benign::{apply_embedding, concat_all, lemma_concat_all_empty};
use crate::machine_group::*;
use crate::kp_pinch::{in_kp_subgroup, is_kp_factor, all_kp_factors, lemma_property_ii};

verus! {

//  ============================================================
//  The ladder predicate
//  ============================================================

//  T(M)-gen, or a LOWER stable letter Gen(3+i)/Inv(3+i) with i < l.
pub open spec fn tmstable_pred_upto(mm: ModMachine, l: nat) -> spec_fn(Word) -> bool {
    |x: Word| is_tm_gen(mm, x)
        || (exists|i: int|
            #![trigger seq![Symbol::Gen((3 + i) as nat)]]
            #![trigger seq![Symbol::Inv((3 + i) as nat)]]
            0 <= i < l
            && (x == seq![Symbol::Gen((3 + i) as nat)] || x == seq![Symbol::Inv((3 + i) as nat)]))
}

//  Membership in ⟨T(M), r/l up to level l⟩ inside b_m_upto(l).
pub open spec fn in_TMstable_upto(mm: ModMachine, l: nat, w: Word) -> bool {
    in_subgroup_pred(b_m_upto(mm, l), tmstable_pred_upto(mm, l), w)
}

//  Named spec_fn value (stable closure identity, like tm_pred / tmstable_pred).
pub open spec fn in_TMstable_upto_pred(mm: ModMachine, l: nat) -> spec_fn(Word) -> bool {
    |x: Word| in_TMstable_upto(mm, l, x)
}

//  The single HNN step that adds level l (quad l-1) over b_m_upto(l-1).
pub open spec fn quad_data(mm: ModMachine, qi: nat) -> HNNData {
    HNNData { base: base_A(), associations: quad_associations(mm.quads[qi as int], mm.m) }
}

//  ============================================================
//  Property (v) hypothesis — the only remaining hole (E2.B).
//  φ maps T(M) into T(M) on each quad's associated subgroup, both directions.
//  Stated over base-A embeddings (the associations live in A, independent of tower level).
//  ============================================================
pub open spec fn prop_v_holds(mm: ModMachine) -> bool {
    forall|qi: nat, uw: Word|
        #![trigger apply_embedding(hnn_a_gens(quad_data(mm, qi)), uw)]
        #![trigger apply_embedding(hnn_b_gens(quad_data(mm, qi)), uw)]
        (qi < mm.quads.len() && word_valid(uw, 3)) ==> {
            &&& (in_TM(mm, apply_embedding(hnn_a_gens(quad_data(mm, qi)), uw))
                    ==> in_TM(mm, apply_embedding(hnn_b_gens(quad_data(mm, qi)), uw)))
            &&& (in_TM(mm, apply_embedding(hnn_b_gens(quad_data(mm, qi)), uw))
                    ==> in_TM(mm, apply_embedding(hnn_a_gens(quad_data(mm, qi)), uw)))
        }
}

//  ============================================================
//  in_subgroup_pred predicate extensionality
//  ============================================================
pub proof fn lemma_in_subgroup_pred_ext(
    p: Presentation, pred1: spec_fn(Word) -> bool, pred2: spec_fn(Word) -> bool, w: Word,
)
    requires
        forall|x: Word| #![trigger pred1(x)] #![trigger pred2(x)] pred1(x) == pred2(x),
    ensures
        in_subgroup_pred(p, pred1, w) == in_subgroup_pred(p, pred2, w),
{
    assert forall|f: Seq<Word>| #[trigger] factors_from_pred(pred1, f) implies factors_from_pred(pred2, f) by {
        assert forall|k: int| 0 <= k < f.len() implies pred2(#[trigger] f[k]) by { assert(pred1(f[k])); }
    }
    assert forall|f: Seq<Word>| #[trigger] factors_from_pred(pred2, f) implies factors_from_pred(pred1, f) by {
        assert forall|k: int| 0 <= k < f.len() implies pred1(#[trigger] f[k]) by { assert(pred2(f[k])); }
    }
    if in_subgroup_pred(p, pred1, w) {
        let f = choose|f: Seq<Word>| #[trigger] factors_from_pred(pred1, f)
            && equiv_in_presentation(p, concat_all(f), w);
        assert(factors_from_pred(pred1, f) && equiv_in_presentation(p, concat_all(f), w));
        assert(factors_from_pred(pred2, f) && equiv_in_presentation(p, concat_all(f), w));
    }
    if in_subgroup_pred(p, pred2, w) {
        let f = choose|f: Seq<Word>| #[trigger] factors_from_pred(pred2, f)
            && equiv_in_presentation(p, concat_all(f), w);
        assert(factors_from_pred(pred2, f) && equiv_in_presentation(p, concat_all(f), w));
        assert(factors_from_pred(pred1, f) && equiv_in_presentation(p, concat_all(f), w));
    }
}

//  ============================================================
//  One-step unfold of the tower presentation
//  ============================================================
pub proof fn lemma_b_m_upto_unfold(mm: ModMachine, l: nat)
    requires
        l >= 1,
    ensures
        b_m_upto(mm, l) == hnn_presentation(HNNData {
            base: b_m_upto(mm, (l - 1) as nat),
            associations: quad_associations(mm.quads[(l - 1) as int], mm.m),
        }),
{
    reveal_with_fuel(b_m_upto, 1);
}

//  ============================================================
//  Endpoint identities
//  ============================================================

//  Level 0 = T(M).
pub proof fn lemma_in_TMstable_upto_zero(mm: ModMachine, w: Word)
    ensures
        in_TMstable_upto(mm, 0, w) == in_TM(mm, w),
{
    assert(b_m_upto(mm, 0) == base_A());
    assert forall|x: Word| #![trigger tmstable_pred_upto(mm, 0)(x)] tmstable_pred_upto(mm, 0)(x) == tm_pred(mm)(x) by {
        assert(!(exists|i: int|
            #![trigger seq![Symbol::Gen((3 + i) as nat)]]
            #![trigger seq![Symbol::Inv((3 + i) as nat)]]
            0 <= i < 0
            && (x == seq![Symbol::Gen((3 + i) as nat)] || x == seq![Symbol::Inv((3 + i) as nat)])));
    }
    lemma_in_subgroup_pred_ext(base_A(), tmstable_pred_upto(mm, 0), tm_pred(mm), w);
}

//  Level N = the full ⟨T(M), rᵢ, lⱼ⟩.
pub proof fn lemma_in_TMstable_upto_full(mm: ModMachine, w: Word)
    ensures
        in_TMstable_upto(mm, mm.quads.len(), w) == in_TMstable(mm, w),
{
    let n = mm.quads.len();
    assert(b_m_upto(mm, n) == b_m(mm));
    assert forall|x: Word| #![trigger tmstable_pred_upto(mm, n)(x)] tmstable_pred_upto(mm, n)(x) == tmstable_pred(mm)(x) by {
        if tmstable_pred_upto(mm, n)(x) {
            if !is_tm_gen(mm, x) {
                let i = choose|i: int|
                    #![trigger seq![Symbol::Gen((3 + i) as nat)]]
                    #![trigger seq![Symbol::Inv((3 + i) as nat)]]
                    0 <= i < n
                    && (x == seq![Symbol::Gen((3 + i) as nat)] || x == seq![Symbol::Inv((3 + i) as nat)]);
                assert(0 <= i < n
                    && (x == seq![Symbol::Gen((3 + i) as nat)] || x == seq![Symbol::Inv((3 + i) as nat)]));
            }
        }
        if tmstable_pred(mm)(x) {
            if !is_tm_gen(mm, x) {
                let i = choose|i: int|
                    #![trigger seq![Symbol::Gen((3 + i) as nat)]]
                    #![trigger seq![Symbol::Inv((3 + i) as nat)]]
                    0 <= i < n
                    && (x == seq![Symbol::Gen((3 + i) as nat)] || x == seq![Symbol::Inv((3 + i) as nat)]);
                assert(0 <= i < n
                    && (x == seq![Symbol::Gen((3 + i) as nat)] || x == seq![Symbol::Inv((3 + i) as nat)]));
            }
        }
    }
    lemma_in_subgroup_pred_ext(b_m(mm), tmstable_pred_upto(mm, n), tmstable_pred(mm), w);
}

//  ============================================================
//  Closure wrappers (the engine's in_k(ε)/H_mul/H_resp hypotheses)
//  ============================================================

pub proof fn lemma_TMstable_upto_empty(mm: ModMachine, l: nat)
    ensures
        in_TMstable_upto(mm, l, empty_word()),
{
    let f = Seq::<Word>::empty();
    lemma_concat_all_empty();
    lemma_equiv_refl(b_m_upto(mm, l), empty_word());
    assert(factors_from_pred(tmstable_pred_upto(mm, l), f));
    assert(in_TMstable_upto(mm, l, empty_word())) by {
        assert(factors_from_pred(tmstable_pred_upto(mm, l), f)
            && equiv_in_presentation(b_m_upto(mm, l), concat_all(f), empty_word()));
    }
}

pub proof fn lemma_TMstable_upto_product(mm: ModMachine, l: nat, w1: Word, w2: Word)
    requires
        in_TMstable_upto(mm, l, w1),
        in_TMstable_upto(mm, l, w2),
    ensures
        in_TMstable_upto(mm, l, w1 + w2),
{
    lemma_product_in_subgroup_pred(b_m_upto(mm, l), tmstable_pred_upto(mm, l), w1, w2);
}

pub proof fn lemma_TMstable_upto_respects(mm: ModMachine, l: nat, v: Word, u: Word)
    requires
        in_TMstable_upto(mm, l, v),
        equiv_in_presentation(b_m_upto(mm, l), v, u),
    ensures
        in_TMstable_upto(mm, l, u),
{
    lemma_in_subgroup_pred_respects_equiv(b_m_upto(mm, l), tmstable_pred_upto(mm, l), v, u);
}

//  ============================================================
//  T(M) ⊆ in_TMstable_upto(l)  (lift T(M) membership up the tower)
//  ============================================================
pub proof fn lemma_in_TM_implies_TMstable_upto(mm: ModMachine, l: nat, w: Word)
    requires
        in_TM(mm, w),
    ensures
        in_TMstable_upto(mm, l, w),
{
    let f = choose|f: Seq<Word>| #[trigger] factors_from_pred(tm_pred(mm), f)
        && equiv_in_presentation(base_A(), concat_all(f), w);
    assert(factors_from_pred(tm_pred(mm), f) && equiv_in_presentation(base_A(), concat_all(f), w));
    lemma_lift_to_bm(mm, l, concat_all(f), w);
    assert(factors_from_pred(tmstable_pred_upto(mm, l), f)) by {
        assert forall|k: int| 0 <= k < f.len() implies tmstable_pred_upto(mm, l)(#[trigger] f[k]) by {
            assert(tm_pred(mm)(f[k]));
        }
    }
    assert(in_TMstable_upto(mm, l, w)) by {
        assert(factors_from_pred(tmstable_pred_upto(mm, l), f)
            && equiv_in_presentation(b_m_upto(mm, l), concat_all(f), w));
    }
}

//  ============================================================
//  data_l validity + isomorphism + presentation identity
//  ============================================================
pub proof fn lemma_quad_step_data_valid(mm: ModMachine, l: nat)
    requires
        mod_machine_wf(mm),
        1 <= l <= mm.quads.len(),
    ensures
        hnn_data_valid(HNNData {
            base: b_m_upto(mm, (l - 1) as nat),
            associations: quad_associations(mm.quads[(l - 1) as int], mm.m),
        }),
        hnn_associations_isomorphic(HNNData {
            base: b_m_upto(mm, (l - 1) as nat),
            associations: quad_associations(mm.quads[(l - 1) as int], mm.m),
        }),
        hnn_presentation(HNNData {
            base: b_m_upto(mm, (l - 1) as nat),
            associations: quad_associations(mm.quads[(l - 1) as int], mm.m),
        }) == b_m_upto(mm, l),
{
    let prev = b_m_upto(mm, (l - 1) as nat);
    let data = HNNData { base: prev, associations: quad_associations(mm.quads[(l - 1) as int], mm.m) };
    lemma_b_m_upto_valid(mm, (l - 1) as nat);
    lemma_b_m_upto_num_generators(mm, (l - 1) as nat);
    lemma_quad_associations_valid(mm.quads[(l - 1) as int], mm.m, prev.num_generators);
    assert(hnn_data_valid(data));
    lemma_b_m_step_isomorphic(mm, (l - 1) as nat);
    lemma_b_m_upto_unfold(mm, l);
}

} //  verus!
