//  ============================================================
//  E2.D — Property (vi) via the tower peel:  A ∩ ⟨T(M),rᵢ,lⱼ⟩ = T(M).
//  ============================================================
//  Own module (trigger isolation).  See docs/e2d-tower-peel-plan.md.
//
//  B(M) is a heterogeneous tower of single-letter HNN steps; every stable letter's associated
//  subgroup lives in the ORIGINAL base A.  We peel the tower top-down, reusing the verified
//  single-letter engine `lemma_property_ii` (kp_pinch, E2.C).
//
//  Ladder predicate `in_TMstable_upto(l)`: the subgroup of `b_m_upto(l)` generated by T(M)-gens +
//  the lower stable letters Gen(3+i), i<l.  Endpoints: level 0 = in_TM, level N = in_TMstable.
//  `lemma_vi_upto(l)`: downward induction; the φ-compatibility hypothesis of the engine is
//  discharged by the IH + property (v) (`prop_v_holds`).

use vstd::prelude::*;
use crate::symbol::*;
use crate::word::*;
use crate::presentation::*;
use crate::hnn::*;
use crate::benign::{apply_embedding, concat_all, lemma_concat_all_empty, lemma_apply_embedding_valid};
use crate::machine_group::*;
use crate::kp_pinch::{in_kp_subgroup, is_kp_factor, all_kp_factors, lemma_property_ii};
use crate::ii_subset::lemma_gexp_config_signed_zero;

verus! {

//  ============================================================
//  The ladder predicate
//  ============================================================

//  T(M)-gen, or a LOWER stable letter Gen(3+i)/Inv(3+i) with i < l.
pub open spec fn tmstable_pred_upto(mm: ModMachine, l: nat) -> spec_fn(Word) -> bool {
    |x: Word| is_tm_gen(mm, x)
        || (exists|i: int|
            #![trigger seq![Symbol::Gen((3 + i) as nat)]]
            #![trigger seq![Symbol::Inv((3 + i) as nat)]]
            0 <= i < l
            && (x == seq![Symbol::Gen((3 + i) as nat)] || x == seq![Symbol::Inv((3 + i) as nat)]))
}

//  Membership in ⟨T(M), r/l up to level l⟩ inside b_m_upto(l).
pub open spec fn in_TMstable_upto(mm: ModMachine, l: nat, w: Word) -> bool {
    in_subgroup_pred(b_m_upto(mm, l), tmstable_pred_upto(mm, l), w)
}

//  Named spec_fn value (stable closure identity, like tm_pred / tmstable_pred).
pub open spec fn in_TMstable_upto_pred(mm: ModMachine, l: nat) -> spec_fn(Word) -> bool {
    |x: Word| in_TMstable_upto(mm, l, x)
}

//  The single HNN step that adds level l (quad l-1) over b_m_upto(l-1) — what the engine peels.
pub open spec fn step_data(mm: ModMachine, l: nat) -> HNNData {
    HNNData {
        base: b_m_upto(mm, (l - 1) as nat),
        associations: quad_associations(mm.quads[(l - 1) as int], mm.m),
    }
}

//  The quad's associations over base A (associations are level-independent; used by prop_v_holds).
pub open spec fn quad_data(mm: ModMachine, qi: nat) -> HNNData {
    HNNData { base: base_A(), associations: quad_associations(mm.quads[qi as int], mm.m) }
}

//  ============================================================
//  Property (v) hypothesis — the only remaining hole (E2.B).
//  φ maps T(M) into T(M) on each quad's associated subgroup, both directions.
//  Stated over base-A embeddings (the associations live in A, independent of tower level).
//  ============================================================
pub open spec fn prop_v_holds(mm: ModMachine) -> bool {
    forall|qi: nat, uw: Word|
        #![trigger apply_embedding(hnn_a_gens(quad_data(mm, qi)), uw)]
        #![trigger apply_embedding(hnn_b_gens(quad_data(mm, qi)), uw)]
        (qi < mm.quads.len() && word_valid(uw, 3)) ==> {
            &&& (in_TM(mm, apply_embedding(hnn_a_gens(quad_data(mm, qi)), uw))
                    ==> in_TM(mm, apply_embedding(hnn_b_gens(quad_data(mm, qi)), uw)))
            &&& (in_TM(mm, apply_embedding(hnn_b_gens(quad_data(mm, qi)), uw))
                    ==> in_TM(mm, apply_embedding(hnn_a_gens(quad_data(mm, qi)), uw)))
        }
}

//  ============================================================
//  in_subgroup_pred predicate extensionality
//  ============================================================
pub proof fn lemma_in_subgroup_pred_ext(
    p: Presentation, pred1: spec_fn(Word) -> bool, pred2: spec_fn(Word) -> bool, w: Word,
)
    requires
        forall|x: Word| #![trigger pred1(x)] #![trigger pred2(x)] pred1(x) == pred2(x),
    ensures
        in_subgroup_pred(p, pred1, w) == in_subgroup_pred(p, pred2, w),
{
    assert forall|f: Seq<Word>| #[trigger] factors_from_pred(pred1, f) implies factors_from_pred(pred2, f) by {
        assert forall|k: int| 0 <= k < f.len() implies pred2(#[trigger] f[k]) by { assert(pred1(f[k])); }
    }
    assert forall|f: Seq<Word>| #[trigger] factors_from_pred(pred2, f) implies factors_from_pred(pred1, f) by {
        assert forall|k: int| 0 <= k < f.len() implies pred1(#[trigger] f[k]) by { assert(pred2(f[k])); }
    }
    if in_subgroup_pred(p, pred1, w) {
        let f = choose|f: Seq<Word>| #[trigger] factors_from_pred(pred1, f)
            && equiv_in_presentation(p, concat_all(f), w);
        assert(factors_from_pred(pred1, f) && equiv_in_presentation(p, concat_all(f), w));
        assert(factors_from_pred(pred2, f) && equiv_in_presentation(p, concat_all(f), w));
    }
    if in_subgroup_pred(p, pred2, w) {
        let f = choose|f: Seq<Word>| #[trigger] factors_from_pred(pred2, f)
            && equiv_in_presentation(p, concat_all(f), w);
        assert(factors_from_pred(pred2, f) && equiv_in_presentation(p, concat_all(f), w));
        assert(factors_from_pred(pred1, f) && equiv_in_presentation(p, concat_all(f), w));
    }
}

//  ============================================================
//  One-step unfold of the tower presentation
//  ============================================================
pub proof fn lemma_b_m_upto_unfold(mm: ModMachine, l: nat)
    requires
        l >= 1,
    ensures
        b_m_upto(mm, l) == hnn_presentation(HNNData {
            base: b_m_upto(mm, (l - 1) as nat),
            associations: quad_associations(mm.quads[(l - 1) as int], mm.m),
        }),
{
    reveal_with_fuel(b_m_upto, 1);
}

//  ============================================================
//  Endpoint identities
//  ============================================================

//  Level 0 = T(M).
pub proof fn lemma_in_TMstable_upto_zero(mm: ModMachine, w: Word)
    ensures
        in_TMstable_upto(mm, 0, w) == in_TM(mm, w),
{
    assert(b_m_upto(mm, 0) == base_A());
    assert forall|x: Word| #![trigger tmstable_pred_upto(mm, 0)(x)] tmstable_pred_upto(mm, 0)(x) == tm_pred(mm)(x) by {
        assert(!(exists|i: int|
            #![trigger seq![Symbol::Gen((3 + i) as nat)]]
            #![trigger seq![Symbol::Inv((3 + i) as nat)]]
            0 <= i < 0
            && (x == seq![Symbol::Gen((3 + i) as nat)] || x == seq![Symbol::Inv((3 + i) as nat)])));
    }
    lemma_in_subgroup_pred_ext(base_A(), tmstable_pred_upto(mm, 0), tm_pred(mm), w);
}

//  Level N = the full ⟨T(M), rᵢ, lⱼ⟩.
pub proof fn lemma_in_TMstable_upto_full(mm: ModMachine, w: Word)
    ensures
        in_TMstable_upto(mm, mm.quads.len(), w) == in_TMstable(mm, w),
{
    let n = mm.quads.len();
    assert(b_m_upto(mm, n) == b_m(mm));
    assert forall|x: Word| #![trigger tmstable_pred_upto(mm, n)(x)] tmstable_pred_upto(mm, n)(x) == tmstable_pred(mm)(x) by {
        if tmstable_pred_upto(mm, n)(x) {
            if !is_tm_gen(mm, x) {
                let i = choose|i: int|
                    #![trigger seq![Symbol::Gen((3 + i) as nat)]]
                    #![trigger seq![Symbol::Inv((3 + i) as nat)]]
                    0 <= i < n
                    && (x == seq![Symbol::Gen((3 + i) as nat)] || x == seq![Symbol::Inv((3 + i) as nat)]);
                assert(0 <= i < n
                    && (x == seq![Symbol::Gen((3 + i) as nat)] || x == seq![Symbol::Inv((3 + i) as nat)]));
            }
        }
        if tmstable_pred(mm)(x) {
            if !is_tm_gen(mm, x) {
                let i = choose|i: int|
                    #![trigger seq![Symbol::Gen((3 + i) as nat)]]
                    #![trigger seq![Symbol::Inv((3 + i) as nat)]]
                    0 <= i < n
                    && (x == seq![Symbol::Gen((3 + i) as nat)] || x == seq![Symbol::Inv((3 + i) as nat)]);
                assert(0 <= i < n
                    && (x == seq![Symbol::Gen((3 + i) as nat)] || x == seq![Symbol::Inv((3 + i) as nat)]));
            }
        }
    }
    lemma_in_subgroup_pred_ext(b_m(mm), tmstable_pred_upto(mm, n), tmstable_pred(mm), w);
}

//  ============================================================
//  Closure wrappers (the engine's in_k(ε)/H_mul/H_resp hypotheses)
//  ============================================================

pub proof fn lemma_TMstable_upto_empty(mm: ModMachine, l: nat)
    ensures
        in_TMstable_upto(mm, l, empty_word()),
{
    let f = Seq::<Word>::empty();
    lemma_concat_all_empty();
    lemma_equiv_refl(b_m_upto(mm, l), empty_word());
    assert(factors_from_pred(tmstable_pred_upto(mm, l), f));
    assert(in_TMstable_upto(mm, l, empty_word())) by {
        assert(factors_from_pred(tmstable_pred_upto(mm, l), f)
            && equiv_in_presentation(b_m_upto(mm, l), concat_all(f), empty_word()));
    }
}

pub proof fn lemma_TMstable_upto_product(mm: ModMachine, l: nat, w1: Word, w2: Word)
    requires
        in_TMstable_upto(mm, l, w1),
        in_TMstable_upto(mm, l, w2),
    ensures
        in_TMstable_upto(mm, l, w1 + w2),
{
    lemma_product_in_subgroup_pred(b_m_upto(mm, l), tmstable_pred_upto(mm, l), w1, w2);
}

pub proof fn lemma_TMstable_upto_respects(mm: ModMachine, l: nat, v: Word, u: Word)
    requires
        in_TMstable_upto(mm, l, v),
        equiv_in_presentation(b_m_upto(mm, l), v, u),
    ensures
        in_TMstable_upto(mm, l, u),
{
    lemma_in_subgroup_pred_respects_equiv(b_m_upto(mm, l), tmstable_pred_upto(mm, l), v, u);
}

//  ============================================================
//  T(M) ⊆ in_TMstable_upto(l)  (lift T(M) membership up the tower)
//  ============================================================
pub proof fn lemma_in_TM_implies_TMstable_upto(mm: ModMachine, l: nat, w: Word)
    requires
        in_TM(mm, w),
    ensures
        in_TMstable_upto(mm, l, w),
{
    let f = choose|f: Seq<Word>| #[trigger] factors_from_pred(tm_pred(mm), f)
        && equiv_in_presentation(base_A(), concat_all(f), w);
    assert(factors_from_pred(tm_pred(mm), f) && equiv_in_presentation(base_A(), concat_all(f), w));
    lemma_lift_to_bm(mm, l, concat_all(f), w);
    assert(factors_from_pred(tmstable_pred_upto(mm, l), f)) by {
        assert forall|k: int| 0 <= k < f.len() implies tmstable_pred_upto(mm, l)(#[trigger] f[k]) by {
            assert(tm_pred(mm)(f[k]));
        }
    }
    assert(in_TMstable_upto(mm, l, w)) by {
        assert(factors_from_pred(tmstable_pred_upto(mm, l), f)
            && equiv_in_presentation(b_m_upto(mm, l), concat_all(f), w));
    }
}

//  ============================================================
//  data_l validity + isomorphism + presentation identity
//  ============================================================
pub proof fn lemma_quad_step_data_valid(mm: ModMachine, l: nat)
    requires
        mod_machine_wf(mm),
        1 <= l <= mm.quads.len(),
    ensures
        hnn_data_valid(step_data(mm, l)),
        hnn_associations_isomorphic(step_data(mm, l)),
        hnn_presentation(step_data(mm, l)) == b_m_upto(mm, l),
        step_data(mm, l).base.num_generators == (3 + (l - 1)) as nat,
{
    let prev = b_m_upto(mm, (l - 1) as nat);
    let data = step_data(mm, l);
    lemma_b_m_upto_valid(mm, (l - 1) as nat);
    lemma_b_m_upto_num_generators(mm, (l - 1) as nat);
    lemma_quad_associations_valid(mm.quads[(l - 1) as int], mm.m, prev.num_generators);
    assert(hnn_data_valid(data));
    lemma_b_m_step_isomorphic(mm, (l - 1) as nat);
    lemma_b_m_upto_unfold(mm, l);
}

//  ============================================================
//  Conversion bridge: in_TMstable_upto(l) ⟹ in_kp_subgroup(step_data, in_TMstable_upto_pred(l-1))
//  ============================================================

//  Each level-l T(M)stable factor is a kp-factor for the top step (K = level l-1):
//  a T(M)-gen / lower stable letter is an in_k base word; the top letter Gen(l+2) is p.
pub proof fn lemma_tmstable_factor_is_kp_factor(mm: ModMachine, l: nat, f: Word)
    requires
        mod_machine_wf(mm),
        1 <= l <= mm.quads.len(),
        tmstable_pred_upto(mm, l)(f),
    ensures
        is_kp_factor(step_data(mm, l), in_TMstable_upto_pred(mm, (l - 1) as nat), f),
{
    let d = step_data(mm, l);
    let ng = d.base.num_generators;
    lemma_b_m_upto_num_generators(mm, (l - 1) as nat);
    assert(ng == (3 + (l - 1)) as nat);
    let in_k = in_TMstable_upto_pred(mm, (l - 1) as nat);
    if is_tm_gen(mm, f) {
        //  Case A: a T(M)-gen.  in_k(f) by lift; word_valid(f, ng) since config words are valid over 3.
        lemma_gen_in_subgroup_pred(base_A(), tm_pred(mm), f);
        lemma_in_TM_implies_TMstable_upto(mm, (l - 1) as nat, f);
        assert(in_k(f));
        let ab = choose|a: nat, b: nat| #![trigger config_word(a, b)]
            mm_in_H0(mm, a, b) && (f == config_word(a, b) || f == inverse_word(config_word(a, b)));
        assert(mm_in_H0(mm, ab.0, ab.1)
            && (f == config_word(ab.0, ab.1) || f == inverse_word(config_word(ab.0, ab.1))));
        lemma_config_word_valid(ab.0, ab.1);
        lemma_inverse_word_valid(config_word(ab.0, ab.1), 3);
        lemma_word_valid_mono(f, 3, ng);
        assert(is_kp_factor(d, in_k, f));
    } else {
        //  Case B: a stable letter Gen(3+i)/Inv(3+i), 0 ≤ i < l.
        let i = choose|i: int|
            #![trigger seq![Symbol::Gen((3 + i) as nat)]]
            #![trigger seq![Symbol::Inv((3 + i) as nat)]]
            0 <= i < l
            && (f == seq![Symbol::Gen((3 + i) as nat)] || f == seq![Symbol::Inv((3 + i) as nat)]);
        assert(0 <= i < l
            && (f == seq![Symbol::Gen((3 + i) as nat)] || f == seq![Symbol::Inv((3 + i) as nat)]));
        if i == l - 1 {
            //  The TOP letter p = Gen(ng) / Inv(ng):  ng == 3+(l-1) == 3+i.
            assert((3 + i) as nat == ng);
            assert(stable_letter(d) == Symbol::Gen(ng));
            assert(stable_letter_inv(d) == Symbol::Inv(ng));
            assert(f == seq![stable_letter(d)] || f == seq![stable_letter_inv(d)]);
            assert(is_kp_factor(d, in_k, f));
        } else {
            //  A LOWER letter, 0 ≤ i < l-1:  in_k(f) (singleton tmstable_pred_upto(l-1)); word_valid.
            assert(0 <= i < (l - 1) as int);
            assert(tmstable_pred_upto(mm, (l - 1) as nat)(f)) by {
                assert(0 <= i < (l - 1)
                    && (f == seq![Symbol::Gen((3 + i) as nat)] || f == seq![Symbol::Inv((3 + i) as nat)]));
            }
            lemma_gen_in_subgroup_pred(b_m_upto(mm, (l - 1) as nat), tmstable_pred_upto(mm, (l - 1) as nat), f);
            assert(in_k(f));
            assert(word_valid(f, ng)) by {
                assert(0 <= i < (l - 1));
                assert((3 + i) < ng);
                assert forall|q: int| 0 <= q < f.len() implies symbol_valid(#[trigger] f[q], ng) by {
                    assert(f[q] == Symbol::Gen((3 + i) as nat) || f[q] == Symbol::Inv((3 + i) as nat));
                }
            }
            assert(is_kp_factor(d, in_k, f));
        }
    }
}

//  The bridge: the SAME factor list of in_TMstable_upto(l) witnesses in_kp_subgroup at the top step.
pub proof fn lemma_TMstable_upto_to_kp(mm: ModMachine, l: nat, w: Word)
    requires
        mod_machine_wf(mm),
        1 <= l <= mm.quads.len(),
        in_TMstable_upto(mm, l, w),
    ensures
        in_kp_subgroup(step_data(mm, l), in_TMstable_upto_pred(mm, (l - 1) as nat), w),
{
    let d = step_data(mm, l);
    let in_k = in_TMstable_upto_pred(mm, (l - 1) as nat);
    lemma_quad_step_data_valid(mm, l);   //  hnn_presentation(d) == b_m_upto(mm, l)
    let factors = choose|factors: Seq<Word>| #[trigger] factors_from_pred(tmstable_pred_upto(mm, l), factors)
        && equiv_in_presentation(b_m_upto(mm, l), concat_all(factors), w);
    assert(factors_from_pred(tmstable_pred_upto(mm, l), factors)
        && equiv_in_presentation(b_m_upto(mm, l), concat_all(factors), w));
    assert(all_kp_factors(d, in_k, factors)) by {
        assert forall|j: int| 0 <= j < factors.len()
            implies is_kp_factor(d, in_k, #[trigger] factors[j]) by {
            assert(tmstable_pred_upto(mm, l)(factors[j]));
            lemma_tmstable_factor_is_kp_factor(mm, l, factors[j]);
        }
    }
    assert(in_kp_subgroup(d, in_k, w)) by {
        assert(all_kp_factors(d, in_k, factors)
            && equiv_in_presentation(hnn_presentation(d), concat_all(factors), w));
    }
}

//  ============================================================
//  φ-compatibility plumbing (the engine's H_ab / H_ba), reduced to prop_v + IH
//  ============================================================

//  hnn_a/b_gens depend only on the (level-independent) associations.
pub proof fn lemma_step_gens_eq(mm: ModMachine, l: nat)
    requires
        1 <= l <= mm.quads.len(),
    ensures
        hnn_a_gens(step_data(mm, l)) == hnn_a_gens(quad_data(mm, (l - 1) as nat)),
        hnn_b_gens(step_data(mm, l)) == hnn_b_gens(quad_data(mm, (l - 1) as nat)),
{
    let d = step_data(mm, l);
    let qd = quad_data(mm, (l - 1) as nat);
    assert(((l - 1) as nat) as int == l - 1);
    assert(d.associations == qd.associations);
    assert(hnn_a_gens(d) =~= hnn_a_gens(qd));
    assert(hnn_b_gens(d) =~= hnn_b_gens(qd));
}

//  The a-side embedding is a base-A word (associations live in A).
pub proof fn lemma_step_a_emb_valid(mm: ModMachine, l: nat, uw: Word)
    requires
        1 <= l <= mm.quads.len(),
        word_valid(uw, 3),
    ensures
        word_valid(apply_embedding(hnn_a_gens(step_data(mm, l)), uw), 3),
{
    let d = step_data(mm, l);
    let ag = hnn_a_gens(d);
    lemma_quad_associations_valid(mm.quads[(l - 1) as int], mm.m, 3);
    assert(d.associations.len() == 3);
    assert(ag.len() == 3);
    assert forall|i: int| 0 <= i < ag.len() implies word_valid(#[trigger] ag[i], 3) by {
        assert(ag[i] == d.associations[i].0);
    }
    lemma_apply_embedding_valid(ag, uw, 3);
}

pub proof fn lemma_step_b_emb_valid(mm: ModMachine, l: nat, uw: Word)
    requires
        1 <= l <= mm.quads.len(),
        word_valid(uw, 3),
    ensures
        word_valid(apply_embedding(hnn_b_gens(step_data(mm, l)), uw), 3),
{
    let d = step_data(mm, l);
    let bg = hnn_b_gens(d);
    lemma_quad_associations_valid(mm.quads[(l - 1) as int], mm.m, 3);
    assert(d.associations.len() == 3);
    assert(bg.len() == 3);
    assert forall|i: int| 0 <= i < bg.len() implies word_valid(#[trigger] bg[i], 3) by {
        assert(bg[i] == d.associations[i].1);
    }
    lemma_apply_embedding_valid(bg, uw, 3);
}

//  prop_v instantiation, A→B side (no IH inside — takes in_TM(aw) as hypothesis).
pub proof fn lemma_phi_ab_step(mm: ModMachine, l: nat, uw: Word)
    requires
        mod_machine_wf(mm),
        prop_v_holds(mm),
        1 <= l <= mm.quads.len(),
        word_valid(uw, 3),
        in_TM(mm, apply_embedding(hnn_a_gens(step_data(mm, l)), uw)),
    ensures
        in_TMstable_upto(mm, (l - 1) as nat, apply_embedding(hnn_b_gens(step_data(mm, l)), uw)),
{
    let qi = (l - 1) as nat;
    lemma_step_gens_eq(mm, l);
    //  aw == quad_data a-embedding; trigger prop_v at qi.
    assert(qi < mm.quads.len());
    assert(in_TM(mm, apply_embedding(hnn_a_gens(quad_data(mm, qi)), uw)));
    assert(in_TM(mm, apply_embedding(hnn_b_gens(quad_data(mm, qi)), uw)));   //  prop_v_holds fires
    assert(in_TM(mm, apply_embedding(hnn_b_gens(step_data(mm, l)), uw)));
    lemma_in_TM_implies_TMstable_upto(mm, qi, apply_embedding(hnn_b_gens(step_data(mm, l)), uw));
}

//  prop_v instantiation, B→A side.
pub proof fn lemma_phi_ba_step(mm: ModMachine, l: nat, uw: Word)
    requires
        mod_machine_wf(mm),
        prop_v_holds(mm),
        1 <= l <= mm.quads.len(),
        word_valid(uw, 3),
        in_TM(mm, apply_embedding(hnn_b_gens(step_data(mm, l)), uw)),
    ensures
        in_TMstable_upto(mm, (l - 1) as nat, apply_embedding(hnn_a_gens(step_data(mm, l)), uw)),
{
    let qi = (l - 1) as nat;
    lemma_step_gens_eq(mm, l);
    assert(qi < mm.quads.len());
    assert(in_TM(mm, apply_embedding(hnn_b_gens(quad_data(mm, qi)), uw)));
    assert(in_TM(mm, apply_embedding(hnn_a_gens(quad_data(mm, qi)), uw)));   //  prop_v_holds fires
    assert(in_TM(mm, apply_embedding(hnn_a_gens(step_data(mm, l)), uw)));
    lemma_in_TM_implies_TMstable_upto(mm, qi, apply_embedding(hnn_a_gens(step_data(mm, l)), uw));
}

//  ============================================================
//  THE INDUCTION — property (vi), top-down tower peel.
//  ============================================================
pub proof fn lemma_vi_upto(mm: ModMachine, l: nat, w: Word)
    requires
        mod_machine_wf(mm),
        mm_terminal(mm, 0, 0),
        prop_v_holds(mm),
        l <= mm.quads.len(),
        in_TMstable_upto(mm, l, w),
        word_valid(w, 3),
    ensures
        in_TM(mm, w),
    decreases l,
{
    if l == 0 {
        lemma_in_TMstable_upto_zero(mm, w);
    } else {
        let d = step_data(mm, l);
        let in_k = in_TMstable_upto_pred(mm, (l - 1) as nat);
        lemma_quad_step_data_valid(mm, l);
        assert(d.associations.len() == 3);

        //  in_k(ε)
        lemma_TMstable_upto_empty(mm, (l - 1) as nat);
        assert(in_k(empty_word()));
        //  H_resp
        assert forall|a: Word, b: Word| in_k(a) && #[trigger] equiv_in_presentation(d.base, a, b)
            implies in_k(b) by {
            lemma_TMstable_upto_respects(mm, (l - 1) as nat, a, b);
        }
        //  H_mul
        assert forall|a: Word, b: Word| in_k(a) && in_k(b) implies in_k(#[trigger] (a + b)) by {
            lemma_TMstable_upto_product(mm, (l - 1) as nat, a, b);
        }
        //  H_ab :  IH(aw) → in_TM(aw) → prop_v → in_k(bw)
        assert forall|uw: Word| word_valid(uw, d.associations.len() as nat)
            && in_k(apply_embedding(hnn_a_gens(d), uw))
            implies in_k(#[trigger] apply_embedding(hnn_b_gens(d), uw)) by {
            let aw = apply_embedding(hnn_a_gens(d), uw);
            assert(word_valid(uw, 3));
            assert(in_TMstable_upto(mm, (l - 1) as nat, aw));   //  = in_k(aw)
            lemma_step_a_emb_valid(mm, l, uw);                  //  word_valid(aw, 3)
            lemma_vi_upto(mm, (l - 1) as nat, aw);              //  IH: in_TM(aw)
            lemma_phi_ab_step(mm, l, uw);                       //  in_k(bw)
        }
        //  H_ba :  symmetric
        assert forall|uw: Word| word_valid(uw, d.associations.len() as nat)
            && in_k(apply_embedding(hnn_b_gens(d), uw))
            implies in_k(#[trigger] apply_embedding(hnn_a_gens(d), uw)) by {
            let bw = apply_embedding(hnn_b_gens(d), uw);
            assert(word_valid(uw, 3));
            assert(in_TMstable_upto(mm, (l - 1) as nat, bw));   //  = in_k(bw)
            lemma_step_b_emb_valid(mm, l, uw);                  //  word_valid(bw, 3)
            lemma_vi_upto(mm, (l - 1) as nat, bw);              //  IH: in_TM(bw)
            lemma_phi_ba_step(mm, l, uw);                       //  in_k(aw)
        }
        //  word_valid(w, d.base.num_generators) and in_kp_subgroup(d, in_k, w)
        lemma_word_valid_mono(w, 3, d.base.num_generators);
        lemma_TMstable_upto_to_kp(mm, l, w);
        //  run the engine ⟹ in_k(w) = in_TMstable_upto(l-1, w)
        lemma_property_ii(d, in_k, w);
        assert(in_TMstable_upto(mm, (l - 1) as nat, w));
        //  recurse one level down
        lemma_vi_upto(mm, (l - 1) as nat, w);
    }
}

//  Property (vi):  A ∩ ⟨T(M), rᵢ, lⱼ⟩ = T(M).
pub proof fn lemma_vi(mm: ModMachine, w: Word)
    requires
        mod_machine_wf(mm),
        mm_terminal(mm, 0, 0),
        prop_v_holds(mm),
        in_TMstable(mm, w),
        word_valid(w, 3),
    ensures
        in_TM(mm, w),
{
    lemma_in_TMstable_upto_full(mm, w);
    assert(in_TMstable_upto(mm, mm.quads.len(), w));
    lemma_vi_upto(mm, mm.quads.len(), w);
}

//  ============================================================
//  Property (v), step 1 (E2.B groundwork):  in_TM ⟹ trivial ⟨x,y⟩-image.
//  This is the precondition (ii)⊆ (`lemma_ii_subset`) needs:  gexp(1)=gexp(2)=0.
//  ============================================================

//  A T(M)-generator (config word or its inverse) has zero x- and y-exponent sum.
pub proof fn lemma_gexp_tm_gen_zero(mm: ModMachine, g: Word, i: nat)
    requires
        i == 1 || i == 2,
        is_tm_gen(mm, g),
    ensures
        gexp(i, g) == 0,
{
    let ab = choose|a: nat, b: nat| #![trigger config_word(a, b)]
        mm_in_H0(mm, a, b) && (g == config_word(a, b) || g == inverse_word(config_word(a, b)));
    assert(g == config_word(ab.0, ab.1) || g == inverse_word(config_word(ab.0, ab.1)));
    lemma_config_signed_matches_nat(ab.0, ab.1);
    lemma_gexp_config_signed_zero(i, ab.0 as int, ab.1 as int);
    assert(gexp(i, config_word(ab.0, ab.1)) == 0);
    if g == inverse_word(config_word(ab.0, ab.1)) {
        lemma_gexp_inverse(i, config_word(ab.0, ab.1));
    }
}

//  A product of T(M)-generators has zero x- and y-exponent sum.
pub proof fn lemma_gexp_tm_factors_zero(mm: ModMachine, f: Seq<Word>, i: nat)
    requires
        i == 1 || i == 2,
        factors_from_pred(tm_pred(mm), f),
    ensures
        gexp(i, concat_all(f)) == 0,
    decreases f.len(),
{
    if f.len() == 0 {
        lemma_concat_all_empty();
    } else {
        reveal_with_fuel(concat_all, 1);
        assert(concat_all(f) == f.first() + concat_all(f.drop_first()));
        assert(tm_pred(mm)(f[0]));
        lemma_gexp_tm_gen_zero(mm, f[0], i);
        assert(factors_from_pred(tm_pred(mm), f.drop_first())) by {
            assert forall|k: int| 0 <= k < f.drop_first().len()
                implies tm_pred(mm)(#[trigger] f.drop_first()[k]) by {
                assert(f.drop_first()[k] == f[k + 1]);
            }
        }
        lemma_gexp_tm_factors_zero(mm, f.drop_first(), i);
        lemma_gexp_concat(i, f.first(), concat_all(f.drop_first()));
    }
}

//  in_TM(w) ⟹ gexp(1,w) = gexp(2,w) = 0.  Feeds (ii)⊆ in the property-(v) reduction.
pub proof fn lemma_in_TM_gexp_zero(mm: ModMachine, w: Word, i: nat)
    requires
        i == 1 || i == 2,
        in_TM(mm, w),
    ensures
        gexp(i, w) == 0,
{
    let f = choose|f: Seq<Word>| #[trigger] factors_from_pred(tm_pred(mm), f)
        && equiv_in_presentation(base_A(), concat_all(f), w);
    assert(factors_from_pred(tm_pred(mm), f) && equiv_in_presentation(base_A(), concat_all(f), w));
    lemma_gexp_tm_factors_zero(mm, f, i);
    lemma_equiv_in_A_preserves_gexp(i, concat_all(f), w);
}

} //  verus!
